// create separate namespace for all the Emscripten stuff.. otherwise naming clashes may occur especially when 
// optimizing using closure compiler..
window.spp_backend_state_mpt= {
	locateFile: function(path, scriptDirectory) { return (typeof window.WASM_SEARCH_PATH == 'undefined') ? path : window.WASM_SEARCH_PATH + path; },
	notReady: true,
	adapterCallback: function(){}	// overwritten later	
};
window.spp_backend_state_mpt["onRuntimeInitialized"] = function() {	// emscripten callback needed in case async init is used (e.g. for WASM)
	this.notReady= false;
	this.adapterCallback();
}.bind(window.spp_backend_state_mpt);

var backend_mpt = (function(Module) {var a;a||(a=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},a),ba="./this.program",ca=(b,c)=>{throw c;},da="object"==typeof window,m="function"==typeof importScripts,t="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,u="",v,ea,fa;
if(t){var fs=require("fs"),ha=require("path");u=m?ha.dirname(u)+"/":__dirname+"/";v=(b,c)=>{b=b.startsWith("file://")?new URL(b):ha.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};fa=b=>{b=v(b,!0);b.buffer||(b=new Uint8Array(b));return b};ea=(b,c,d)=>{b=b.startsWith("file://")?new URL(b):ha.normalize(b);fs.readFile(b,function(e,f){e?d(e):c(f.buffer)})};1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=a);process.on("uncaughtException",
function(b){if(!(b instanceof ia))throw b;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",function(b){throw b;});ca=(b,c)=>{if(noExitRuntime)throw process.exitCode=b,c;if(!(c instanceof ia)){var d=c;c&&"object"==typeof c&&c.stack&&(d=[c,c.stack]);y("exiting due to exception: "+d)}process.exit(b)};a.inspect=function(){return"[Emscripten Module object]"}}else if(da||m)m?u=self.location.href:"undefined"!=typeof document&&document.currentScript&&(u=document.currentScript.src),
u=0!==u.indexOf("blob:")?u.substr(0,u.replace(/[?#].*/,"").lastIndexOf("/")+1):"",v=b=>{var c=new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},m&&(fa=b=>{var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),ea=(b,c,d)=>{var e=new XMLHttpRequest;e.open("GET",b,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d()};e.onerror=d;e.send(null)};
var ja=a.print||console.log.bind(console),y=a.printErr||console.warn.bind(console);Object.assign(a,aa);aa=null;a.thisProgram&&(ba=a.thisProgram);a.quit&&(ca=a.quit);var ka;a.wasmBinary&&(ka=a.wasmBinary);var noExitRuntime=a.noExitRuntime||!0;"object"!=typeof WebAssembly&&z("no native wasm support detected");var la,ma=!1,na="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function oa(b,c,d){var e=c+d;for(d=c;b[d]&&!(d>=e);)++d;if(16<d-c&&b.buffer&&na)return na.decode(b.subarray(c,d));for(e="";c<d;){var f=b[c++];if(f&128){var g=b[c++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var k=b[c++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|b[c++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function C(b,c){return b?oa(pa,b,c):""}
function qa(b,c,d,e){if(!(0<e))return 0;var f=d;e=d+e-1;for(var g=0;g<b.length;++g){var k=b.charCodeAt(g);if(55296<=k&&57343>=k){var l=b.charCodeAt(++g);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(d>=e)break;c[d++]=k}else{if(2047>=k){if(d+1>=e)break;c[d++]=192|k>>6}else{if(65535>=k){if(d+2>=e)break;c[d++]=224|k>>12}else{if(d+3>=e)break;c[d++]=240|k>>18;c[d++]=128|k>>12&63}c[d++]=128|k>>6&63}c[d++]=128|k&63}}c[d]=0;return d-f}var D,pa,F,G,ra,sa=[],ta=[],ua=[];
function va(){var b=a.preRun.shift();sa.unshift(b)}var I=0,wa=null,xa=null;function ya(){I++;a.monitorRunDependencies&&a.monitorRunDependencies(I)}function za(){I--;a.monitorRunDependencies&&a.monitorRunDependencies(I);if(0==I&&(null!==wa&&(clearInterval(wa),wa=null),xa)){var b=xa;xa=null;b()}}function z(b){if(a.onAbort)a.onAbort(b);b="Aborted("+b+")";y(b);ma=!0;throw new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");}
function Aa(b){return b.startsWith("data:application/octet-stream;base64,")}var J;J="mpt.wasm";if(!Aa(J)){var Ba=J;J=a.locateFile?a.locateFile(Ba,u):u+Ba}function Ca(b){try{if(b==J&&ka)return new Uint8Array(ka);if(fa)return fa(b);throw"both async and sync fetching of the wasm failed";}catch(c){z(c)}}
function Da(b){if(!ka&&(da||m)){if("function"==typeof fetch&&!b.startsWith("file://"))return fetch(b,{credentials:"same-origin"}).then(function(c){if(!c.ok)throw"failed to load wasm binary file at '"+b+"'";return c.arrayBuffer()}).catch(function(){return Ca(b)});if(ea)return new Promise(function(c,d){ea(b,function(e){c(new Uint8Array(e))},d)})}return Promise.resolve().then(function(){return Ca(b)})}
function Ea(b,c,d){return Da(b).then(function(e){return WebAssembly.instantiate(e,c)}).then(function(e){return e}).then(d,function(e){y("failed to asynchronously prepare wasm: "+e);z(e)})}
function Fa(b,c){var d=J;ka||"function"!=typeof WebAssembly.instantiateStreaming||Aa(d)||d.startsWith("file://")||t||"function"!=typeof fetch?Ea(d,b,c):fetch(d,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,b).then(c,function(f){y("wasm streaming compile failed: "+f);y("falling back to ArrayBuffer instantiation");return Ea(d,b,c)})})}var K,Ga;function ia(b){this.name="ExitStatus";this.message="Program terminated with exit("+b+")";this.status=b}
function Ha(b){for(;0<b.length;)b.shift()(a)}var Ia=[],Ja=0,M=0,Ka=[];function N(b){var c=Ka[b];c||(b>=Ka.length&&(Ka.length=b+1),Ka[b]=c=ra.get(b));return c}
function La(b){this.Yf=b;this.Lf=b-24;this.Fg=function(c){G[this.Lf+4>>2]=c};this.Mf=function(){return G[this.Lf+4>>2]};this.Dg=function(c){G[this.Lf+8>>2]=c};this.Jg=function(){return G[this.Lf+8>>2]};this.Eg=function(){F[this.Lf>>2]=0};this.jg=function(c){D[this.Lf+12>>0]=c?1:0};this.Ag=function(){return 0!=D[this.Lf+12>>0]};this.kg=function(c){D[this.Lf+13>>0]=c?1:0};this.sg=function(){return 0!=D[this.Lf+13>>0]};this.Cg=function(c,d){this.$f(0);this.Fg(c);this.Dg(d);this.Eg();this.jg(!1);this.kg(!1)};
this.yg=function(){F[this.Lf>>2]+=1};this.Ng=function(){var c=F[this.Lf>>2];F[this.Lf>>2]=c-1;return 1===c};this.$f=function(c){G[this.Lf+16>>2]=c};this.zg=function(){return G[this.Lf+16>>2]};this.Bg=function(){if(Ma(this.Mf()))return G[this.Yf>>2];var c=this.zg();return 0!==c?c:this.Yf}}
function Na(){var b=M;if(!b)return Oa(0),0;var c=new La(b);c.$f(b);var d=c.Mf();if(!d)return Oa(0),b;for(var e=0;e<arguments.length;e++){var f=arguments[e];if(0===f||f===d)break;if(Pa(f,d,c.Lf+16))return Oa(f),b}Oa(d);return b}var Qa;Qa=t?()=>{var b=process.hrtime();return 1E3*b[0]+b[1]/1E6}:()=>performance.now();var Ra={};
function Sa(){if(!Ta){var b={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},c;for(c in Ra)void 0===Ra[c]?delete b[c]:b[c]=Ra[c];var d=[];for(c in b)d.push(c+"="+b[c]);Ta=d}return Ta}
var Ta,Ua=(b,c)=>{for(var d=0,e=b.length-1;0<=e;e--){var f=b[e];"."===f?b.splice(e,1):".."===f?(b.splice(e,1),d++):d&&(b.splice(e,1),d--)}if(c)for(;d;d--)b.unshift("..");return b},O=b=>{var c="/"===b.charAt(0),d="/"===b.substr(-1);(b=Ua(b.split("/").filter(e=>!!e),!c).join("/"))||c||(b=".");b&&d&&(b+="/");return(c?"/":"")+b},Va=b=>{var c=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(b).slice(1);b=c[0];c=c[1];if(!b&&!c)return".";c&&(c=c.substr(0,c.length-1));return b+c},Wa=b=>
{if("/"===b)return"/";b=O(b);b=b.replace(/\/$/,"");var c=b.lastIndexOf("/");return-1===c?b:b.substr(c+1)};function Xa(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var b=new Uint8Array(1);return()=>{crypto.getRandomValues(b);return b[0]}}if(t)try{var c=require("crypto");return()=>c.randomBytes(1)[0]}catch(d){}return()=>z("randomDevice")}
function Ya(){for(var b="",c=!1,d=arguments.length-1;-1<=d&&!c;d--){c=0<=d?arguments[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ua(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."}function Za(b,c){for(var d=0,e=0;e<b.length;++e){var f=b.charCodeAt(e);127>=f?d++:2047>=f?d+=2:55296<=f&&57343>=f?(d+=4,++e):d+=3}d=Array(d+1);b=qa(b,d,0,d.length);c&&(d.length=b);return d}var $a=[];
function ab(b,c){$a[b]={input:[],output:[],Wf:c};bb(b,cb)}
var cb={open:function(b){var c=$a[b.node.rdev];if(!c)throw new P(43);b.tty=c;b.seekable=!1},close:function(b){b.tty.Wf.fsync(b.tty)},fsync:function(b){b.tty.Wf.fsync(b.tty)},read:function(b,c,d,e){if(!b.tty||!b.tty.Wf.rg)throw new P(60);for(var f=0,g=0;g<e;g++){try{var k=b.tty.Wf.rg(b.tty)}catch(l){throw new P(29);}if(void 0===k&&0===f)throw new P(6);if(null===k||void 0===k)break;f++;c[d+g]=k}f&&(b.node.timestamp=Date.now());return f},write:function(b,c,d,e){if(!b.tty||!b.tty.Wf.hg)throw new P(60);
try{for(var f=0;f<e;f++)b.tty.Wf.hg(b.tty,c[d+f])}catch(g){throw new P(29);}e&&(b.node.timestamp=Date.now());return f}},db={rg:function(b){if(!b.input.length){var c=null;if(t){var d=Buffer.alloc(256),e=0;try{e=fs.readSync(process.stdin.fd,d,0,256,-1)}catch(f){if(f.toString().includes("EOF"))e=0;else throw f;}0<e?c=d.slice(0,e).toString("utf-8"):c=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(c=window.prompt("Input: "),null!==c&&(c+="\n")):"function"==typeof readline&&(c=readline(),
null!==c&&(c+="\n"));if(!c)return null;b.input=Za(c,!0)}return b.input.shift()},hg:function(b,c){null===c||10===c?(ja(oa(b.output,0)),b.output=[]):0!=c&&b.output.push(c)},fsync:function(b){b.output&&0<b.output.length&&(ja(oa(b.output,0)),b.output=[])}},eb={hg:function(b,c){null===c||10===c?(y(oa(b.output,0)),b.output=[]):0!=c&&b.output.push(c)},fsync:function(b){b.output&&0<b.output.length&&(y(oa(b.output,0)),b.output=[])}},Q={Of:null,Qf:function(){return Q.createNode(null,"/",16895,0)},createNode:function(b,
c,d,e){if(24576===(d&61440)||4096===(d&61440))throw new P(63);Q.Of||(Q.Of={dir:{node:{Rf:Q.If.Rf,Nf:Q.If.Nf,lookup:Q.If.lookup,ag:Q.If.ag,rename:Q.If.rename,unlink:Q.If.unlink,rmdir:Q.If.rmdir,readdir:Q.If.readdir,symlink:Q.If.symlink},stream:{Sf:Q.Jf.Sf}},file:{node:{Rf:Q.If.Rf,Nf:Q.If.Nf},stream:{Sf:Q.Jf.Sf,read:Q.Jf.read,write:Q.Jf.write,mg:Q.Jf.mg,gg:Q.Jf.gg,wg:Q.Jf.wg}},link:{node:{Rf:Q.If.Rf,Nf:Q.If.Nf,readlink:Q.If.readlink},stream:{}},og:{node:{Rf:Q.If.Rf,Nf:Q.If.Nf},stream:fb}});d=gb(b,c,
d,e);16384===(d.mode&61440)?(d.If=Q.Of.dir.node,d.Jf=Q.Of.dir.stream,d.Hf={}):32768===(d.mode&61440)?(d.If=Q.Of.file.node,d.Jf=Q.Of.file.stream,d.Kf=0,d.Hf=null):40960===(d.mode&61440)?(d.If=Q.Of.link.node,d.Jf=Q.Of.link.stream):8192===(d.mode&61440)&&(d.If=Q.Of.og.node,d.Jf=Q.Of.og.stream);d.timestamp=Date.now();b&&(b.Hf[c]=d,b.timestamp=d.timestamp);return d},Wg:function(b){return b.Hf?b.Hf.subarray?b.Hf.subarray(0,b.Kf):new Uint8Array(b.Hf):new Uint8Array(0)},pg:function(b,c){var d=b.Hf?b.Hf.length:
0;d>=c||(c=Math.max(c,d*(1048576>d?2:1.125)>>>0),0!=d&&(c=Math.max(c,256)),d=b.Hf,b.Hf=new Uint8Array(c),0<b.Kf&&b.Hf.set(d.subarray(0,b.Kf),0))},Og:function(b,c){if(b.Kf!=c)if(0==c)b.Hf=null,b.Kf=0;else{var d=b.Hf;b.Hf=new Uint8Array(c);d&&b.Hf.set(d.subarray(0,Math.min(c,b.Kf)));b.Kf=c}},If:{Rf:function(b){var c={};c.dev=8192===(b.mode&61440)?b.id:1;c.ino=b.id;c.mode=b.mode;c.nlink=1;c.uid=0;c.gid=0;c.rdev=b.rdev;16384===(b.mode&61440)?c.size=4096:32768===(b.mode&61440)?c.size=b.Kf:40960===(b.mode&
61440)?c.size=b.link.length:c.size=0;c.atime=new Date(b.timestamp);c.mtime=new Date(b.timestamp);c.ctime=new Date(b.timestamp);c.Ig=4096;c.blocks=Math.ceil(c.size/c.Ig);return c},Nf:function(b,c){void 0!==c.mode&&(b.mode=c.mode);void 0!==c.timestamp&&(b.timestamp=c.timestamp);void 0!==c.size&&Q.Og(b,c.size)},lookup:function(){throw hb[44];},ag:function(b,c,d,e){return Q.createNode(b,c,d,e)},rename:function(b,c,d){if(16384===(b.mode&61440)){try{var e=R(c,d)}catch(g){}if(e)for(var f in e.Hf)throw new P(55);
}delete b.parent.Hf[b.name];b.parent.timestamp=Date.now();b.name=d;c.Hf[d]=b;c.timestamp=b.parent.timestamp;b.parent=c},unlink:function(b,c){delete b.Hf[c];b.timestamp=Date.now()},rmdir:function(b,c){var d=R(b,c),e;for(e in d.Hf)throw new P(55);delete b.Hf[c];b.timestamp=Date.now()},readdir:function(b){var c=[".",".."],d;for(d in b.Hf)b.Hf.hasOwnProperty(d)&&c.push(d);return c},symlink:function(b,c,d){b=Q.createNode(b,c,41471,0);b.link=d;return b},readlink:function(b){if(40960!==(b.mode&61440))throw new P(28);
return b.link}},Jf:{read:function(b,c,d,e,f){var g=b.node.Hf;if(f>=b.node.Kf)return 0;b=Math.min(b.node.Kf-f,e);if(8<b&&g.subarray)c.set(g.subarray(f,f+b),d);else for(e=0;e<b;e++)c[d+e]=g[f+e];return b},write:function(b,c,d,e,f,g){if(!e)return 0;b=b.node;b.timestamp=Date.now();if(c.subarray&&(!b.Hf||b.Hf.subarray)){if(g)return b.Hf=c.subarray(d,d+e),b.Kf=e;if(0===b.Kf&&0===f)return b.Hf=c.slice(d,d+e),b.Kf=e;if(f+e<=b.Kf)return b.Hf.set(c.subarray(d,d+e),f),e}Q.pg(b,f+e);if(b.Hf.subarray&&c.subarray)b.Hf.set(c.subarray(d,
d+e),f);else for(g=0;g<e;g++)b.Hf[f+g]=c[d+g];b.Kf=Math.max(b.Kf,f+e);return e},Sf:function(b,c,d){1===d?c+=b.position:2===d&&32768===(b.node.mode&61440)&&(c+=b.node.Kf);if(0>c)throw new P(28);return c},mg:function(b,c,d){Q.pg(b.node,c+d);b.node.Kf=Math.max(b.node.Kf,c+d)},gg:function(b,c,d,e,f){if(32768!==(b.node.mode&61440))throw new P(43);b=b.node.Hf;if(f&2||b.buffer!==D.buffer){if(0<d||d+c<b.length)b.subarray?b=b.subarray(d,d+c):b=Array.prototype.slice.call(b,d,d+c);d=!0;z();c=void 0;if(!c)throw new P(48);
D.set(b,c)}else d=!1,c=b.byteOffset;return{Lf:c,Vg:d}},wg:function(b,c,d,e){Q.Jf.write(b,c,0,e,d,!1);return 0}}};function ib(b,c,d){var e="al "+b;ea(b,f=>{f||z('Loading data file "'+b+'" failed (no arrayBuffer).');c(new Uint8Array(f));e&&za(e)},()=>{if(d)d();else throw'Loading data file "'+b+'" failed.';});e&&ya(e)}
var jb=null,kb={},lb=[],mb=1,S=null,nb=!0,P=null,hb={},T=(b,c={})=>{b=Ya(b);if(!b)return{path:"",node:null};c=Object.assign({qg:!0,ig:0},c);if(8<c.ig)throw new P(32);b=b.split("/").filter(k=>!!k);for(var d=jb,e="/",f=0;f<b.length;f++){var g=f===b.length-1;if(g&&c.parent)break;d=R(d,b[f]);e=O(e+"/"+b[f]);d.Zf&&(!g||g&&c.qg)&&(d=d.Zf.root);if(!g||c.dg)for(g=0;40960===(d.mode&61440);)if(d=ob(e),e=Ya(Va(e),d),d=T(e,{ig:c.ig+1}).node,40<g++)throw new P(32);}return{path:e,node:d}},U=b=>{for(var c;;){if(b===
b.parent)return b=b.Qf.vg,c?"/"!==b[b.length-1]?b+"/"+c:b+c:b;c=c?b.name+"/"+c:b.name;b=b.parent}},pb=(b,c)=>{for(var d=0,e=0;e<c.length;e++)d=(d<<5)-d+c.charCodeAt(e)|0;return(b+d>>>0)%S.length},R=(b,c)=>{var d;if(d=(d=qb(b,"x"))?d:b.If.lookup?0:2)throw new P(d,b);for(d=S[pb(b.id,c)];d;d=d.Vf){var e=d.name;if(d.parent.id===b.id&&e===c)return d}return b.If.lookup(b,c)},gb=(b,c,d,e)=>{b=new rb(b,c,d,e);c=pb(b.parent.id,b.name);b.Vf=S[c];return S[c]=b},sb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},
tb=b=>{var c=["r","w","rw"][b&3];b&512&&(c+="w");return c},qb=(b,c)=>{if(nb)return 0;if(!c.includes("r")||b.mode&292){if(c.includes("w")&&!(b.mode&146)||c.includes("x")&&!(b.mode&73))return 2}else return 2;return 0},ub=(b,c)=>{try{return R(b,c),20}catch(d){}return qb(b,"wx")},vb=()=>{for(var b=0;4096>=b;b++)if(!lb[b])return b;throw new P(33);},xb=b=>{wb||(wb=function(){this.Mf={}},wb.prototype={},Object.defineProperties(wb.prototype,{object:{get:function(){return this.node},set:function(d){this.node=
d}},flags:{get:function(){return this.Mf.flags},set:function(d){this.Mf.flags=d}},position:{get:function(){return this.Mf.position},set:function(d){this.Mf.position=d}}}));b=Object.assign(new wb,b);var c=vb();b.fd=c;return lb[c]=b},fb={open:b=>{b.Jf=kb[b.node.rdev].Jf;b.Jf.open&&b.Jf.open(b)},Sf:()=>{throw new P(70);}},bb=(b,c)=>{kb[b]={Jf:c}},yb=(b,c)=>{var d="/"===c,e=!c;if(d&&jb)throw new P(10);if(!d&&!e){var f=T(c,{qg:!1});c=f.path;f=f.node;if(f.Zf)throw new P(10);if(16384!==(f.mode&61440))throw new P(54);
}c={type:b,Yg:{},vg:c,Mg:[]};b=b.Qf(c);b.Qf=c;c.root=b;d?jb=b:f&&(f.Zf=c,f.Qf&&f.Qf.Mg.push(c))},V=(b,c,d)=>{var e=T(b,{parent:!0}).node;b=Wa(b);if(!b||"."===b||".."===b)throw new P(28);var f=ub(e,b);if(f)throw new P(f);if(!e.If.ag)throw new P(63);return e.If.ag(e,b,c,d)},zb=(b,c,d)=>{"undefined"==typeof d&&(d=c,c=438);return V(b,c|8192,d)},Ab=(b,c)=>{if(!Ya(b))throw new P(44);var d=T(c,{parent:!0}).node;if(!d)throw new P(44);c=Wa(c);var e=ub(d,c);if(e)throw new P(e);if(!d.If.symlink)throw new P(63);
d.If.symlink(d,c,b)},Bb=b=>{var c=T(b,{parent:!0}).node;if(!c)throw new P(44);var d=Wa(b);b=R(c,d);a:{try{var e=R(c,d)}catch(g){e=g.Xf;break a}var f=qb(c,"wx");e=f?f:16384===(e.mode&61440)?31:0}if(e)throw new P(e);if(!c.If.unlink)throw new P(63);if(b.Zf)throw new P(10);c.If.unlink(c,d);c=pb(b.parent.id,b.name);if(S[c]===b)S[c]=b.Vf;else for(c=S[c];c;){if(c.Vf===b){c.Vf=b.Vf;break}c=c.Vf}},ob=b=>{b=T(b).node;if(!b)throw new P(44);if(!b.If.readlink)throw new P(28);return Ya(U(b.parent),b.If.readlink(b))},
Cb=(b,c)=>{b="string"==typeof b?T(b,{dg:!0}).node:b;if(!b.If.Nf)throw new P(63);b.If.Nf(b,{mode:c&4095|b.mode&-4096,timestamp:Date.now()})},Eb=(b,c)=>{if(""===b)throw new P(44);if("string"==typeof c){var d=sb[c];if("undefined"==typeof d)throw Error("Unknown file open mode: "+c);c=d}var e=c&64?("undefined"==typeof e?438:e)&4095|32768:0;if("object"==typeof b)var f=b;else{b=O(b);try{f=T(b,{dg:!(c&131072)}).node}catch(g){}}d=!1;if(c&64)if(f){if(c&128)throw new P(20);}else f=V(b,e,0),d=!0;if(!f)throw new P(44);
8192===(f.mode&61440)&&(c&=-513);if(c&65536&&16384!==(f.mode&61440))throw new P(54);if(!d&&(e=f?40960===(f.mode&61440)?32:16384===(f.mode&61440)&&("r"!==tb(c)||c&512)?31:qb(f,tb(c)):44))throw new P(e);if(c&512&&!d){e=f;e="string"==typeof e?T(e,{dg:!0}).node:e;if(!e.If.Nf)throw new P(63);if(16384===(e.mode&61440))throw new P(31);if(32768!==(e.mode&61440))throw new P(28);if(d=qb(e,"w"))throw new P(d);e.If.Nf(e,{size:0,timestamp:Date.now()})}c&=-131713;f=xb({node:f,path:U(f),flags:c,seekable:!0,position:0,
Jf:f.Jf,Ug:[],error:!1});f.Jf.open&&f.Jf.open(f);!a.logReadFiles||c&1||(Db||(Db={}),b in Db||(Db[b]=1));return f},Fb=b=>{if(null===b.fd)throw new P(8);b.eg&&(b.eg=null);try{b.Jf.close&&b.Jf.close(b)}catch(c){throw c;}finally{lb[b.fd]=null}b.fd=null},Gb=(b,c,d)=>{if(null===b.fd)throw new P(8);if(!b.seekable||!b.Jf.Sf)throw new P(70);if(0!=d&&1!=d&&2!=d)throw new P(28);b.position=b.Jf.Sf(b,c,d);b.Ug=[]},Hb=(b,c,d,e,f,g)=>{if(0>e||0>f)throw new P(28);if(null===b.fd)throw new P(8);if(0===(b.flags&2097155))throw new P(8);
if(16384===(b.node.mode&61440))throw new P(31);if(!b.Jf.write)throw new P(28);b.seekable&&b.flags&1024&&Gb(b,0,2);var k="undefined"!=typeof f;if(!k)f=b.position;else if(!b.seekable)throw new P(70);c=b.Jf.write(b,c,d,e,f,g);k||(b.position+=c);return c},Ib=()=>{P||(P=function(b,c){this.name="ErrnoError";this.node=c;this.Pg=function(d){this.Xf=d};this.Pg(b);this.message="FS error"},P.prototype=Error(),P.prototype.constructor=P,[44].forEach(b=>{hb[b]=new P(b);hb[b].stack="<generic error, no stack>"}))},
Jb,Kb=(b,c)=>{var d=0;b&&(d|=365);c&&(d|=146);return d},Lb=(b,c)=>{b="string"==typeof b?b:U(b);for(c=c.split("/").reverse();c.length;){var d=c.pop();if(d){var e=O(b+"/"+d);try{V(e,16895,0)}catch(f){}b=e}}return e},Mb=(b,c,d,e)=>{b=O(("string"==typeof b?b:U(b))+"/"+c);d=Kb(d,e);return V(b,(void 0!==d?d:438)&4095|32768,0)},Nb=(b,c,d,e,f,g)=>{var k=c;b&&(b="string"==typeof b?b:U(b),k=c?O(b+"/"+c):b);b=Kb(e,f);k=V(k,(void 0!==b?b:438)&4095|32768,0);if(d){if("string"==typeof d){c=Array(d.length);e=0;for(f=
d.length;e<f;++e)c[e]=d.charCodeAt(e);d=c}Cb(k,b|146);c=Eb(k,577);Hb(c,d,0,d.length,0,g);Fb(c);Cb(k,b)}return k},W=(b,c,d,e)=>{b=O(("string"==typeof b?b:U(b))+"/"+c);c=Kb(!!d,!!e);W.ug||(W.ug=64);var f=W.ug++<<8|0;bb(f,{open:g=>{g.seekable=!1},close:()=>{e&&e.buffer&&e.buffer.length&&e(10)},read:(g,k,l,q)=>{for(var n=0,p=0;p<q;p++){try{var r=d()}catch(A){throw new P(29);}if(void 0===r&&0===n)throw new P(6);if(null===r||void 0===r)break;n++;k[l+p]=r}n&&(g.node.timestamp=Date.now());return n},write:(g,
k,l,q)=>{for(var n=0;n<q;n++)try{e(k[l+n])}catch(p){throw new P(29);}q&&(g.node.timestamp=Date.now());return n}});return zb(b,c,f)},Ob=b=>{if(!(b.Kg||b.Lg||b.link||b.Hf)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(v)try{b.Hf=Za(v(b.url),!0),b.Kf=b.Hf.length}catch(c){throw new P(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");
}},Pb=(b,c,d,e,f)=>{function g(){this.fg=!1;this.Mf=[]}g.prototype.get=function(p){if(!(p>this.length-1||0>p)){var r=p%this.chunkSize;return this.tg(p/this.chunkSize|0)[r]}};g.prototype.$f=function(p){this.tg=p};g.prototype.ng=function(){var p=new XMLHttpRequest;p.open("HEAD",d,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+d+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),A,h=(A=p.getResponseHeader("Accept-Ranges"))&&"bytes"===
A;p=(A=p.getResponseHeader("Content-Encoding"))&&"gzip"===A;var w=1048576;h||(w=r);var x=this;x.$f(B=>{var E=B*w,L=(B+1)*w-1;L=Math.min(L,r-1);if("undefined"==typeof x.Mf[B]){var lc=x.Mf;if(E>L)throw Error("invalid range ("+E+", "+L+") or no bytes requested!");if(L>r-1)throw Error("only "+r+" bytes available! programmer error!");var H=new XMLHttpRequest;H.open("GET",d,!1);r!==w&&H.setRequestHeader("Range","bytes="+E+"-"+L);H.responseType="arraybuffer";H.overrideMimeType&&H.overrideMimeType("text/plain; charset=x-user-defined");
H.send(null);if(!(200<=H.status&&300>H.status||304===H.status))throw Error("Couldn't load "+d+". Status: "+H.status);E=void 0!==H.response?new Uint8Array(H.response||[]):Za(H.responseText||"",!0);lc[B]=E}if("undefined"==typeof x.Mf[B])throw Error("doXHR failed!");return x.Mf[B]});if(p||!r)w=r=1,w=r=this.tg(0).length,ja("LazyFiles on gzip forces download of the whole file when length is accessed");this.Hg=r;this.Gg=w;this.fg=!0};if("undefined"!=typeof XMLHttpRequest){if(!m)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var k=new g;Object.defineProperties(k,{length:{get:function(){this.fg||this.ng();return this.Hg}},chunkSize:{get:function(){this.fg||this.ng();return this.Gg}}});var l=void 0}else l=d,k=void 0;var q=Mb(b,c,e,f);k?q.Hf=k:l&&(q.Hf=null,q.url=l);Object.defineProperties(q,{Kf:{get:function(){return this.Hf.length}}});var n={};Object.keys(q.Jf).forEach(p=>{var r=q.Jf[p];n[p]=function(){Ob(q);return r.apply(null,arguments)}});n.read=(p,r,A,h,w)=>{Ob(q);p=p.node.Hf;if(w>=p.length)r=0;else{h=Math.min(p.length-
w,h);if(p.slice)for(var x=0;x<h;x++)r[A+x]=p[w+x];else for(x=0;x<h;x++)r[A+x]=p.get(w+x);r=h}return r};n.gg=()=>{Ob(q);z();throw new P(48);};q.Jf=n;return q},Rb=(b,c,d,e,f,g,k,l,q,n)=>{function p(h){function w(x){n&&n();l||Nb(b,c,x,e,f,q);g&&g();za(A)}Qb.Xg(h,r,w,()=>{k&&k();za(A)})||w(h)}var r=c?Ya(O(b+"/"+c)):b,A="cp "+r;ya(A);"string"==typeof d?ib(d,h=>p(h),k):p(d)},Sb={},wb,Db;function Tb(b){b=lb[b];if(!b)throw new P(8);return b}
function Ub(b,c){Ub.xg||(Ub.xg=Xa());for(var d=0;d<c;d++)D[b+d>>0]=Ub.xg();return 0}function Vb(b){return 0===b%4&&(0!==b%100||0===b%400)}var Wb=[31,29,31,30,31,30,31,31,30,31,30,31],Xb=[31,28,31,30,31,30,31,31,30,31,30,31];
function Yb(b,c,d,e){function f(h,w,x){for(h="number"==typeof h?h.toString():h||"";h.length<w;)h=x[0]+h;return h}function g(h,w){return f(h,w,"0")}function k(h,w){function x(E){return 0>E?-1:0<E?1:0}var B;0===(B=x(h.getFullYear()-w.getFullYear()))&&0===(B=x(h.getMonth()-w.getMonth()))&&(B=x(h.getDate()-w.getDate()));return B}function l(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function q(h){var w=h.Tf;for(h=new Date((new Date(h.Uf+1900,0,1)).getTime());0<w;){var x=h.getMonth(),B=(Vb(h.getFullYear())?Wb:Xb)[x];if(w>B-h.getDate())w-=B-h.getDate()+1,h.setDate(1),11>x?h.setMonth(x+1):(h.setMonth(0),h.setFullYear(h.getFullYear()+1));else{h.setDate(h.getDate()+w);break}}x=new Date(h.getFullYear()+1,0,4);w=l(new Date(h.getFullYear(),
0,4));x=l(x);return 0>=k(w,h)?0>=k(x,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var n=F[e+40>>2];e={Sg:F[e>>2],Rg:F[e+4>>2],bg:F[e+8>>2],lg:F[e+12>>2],cg:F[e+16>>2],Uf:F[e+20>>2],Pf:F[e+24>>2],Tf:F[e+28>>2],Zg:F[e+32>>2],Qg:F[e+36>>2],Tg:n?C(n):""};d=C(d);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d",
"%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in n)d=d.replace(new RegExp(p,"g"),n[p]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),A="January February March April May June July August September October November December".split(" ");n={"%a":function(h){return r[h.Pf].substring(0,3)},"%A":function(h){return r[h.Pf]},"%b":function(h){return A[h.cg].substring(0,3)},"%B":function(h){return A[h.cg]},
"%C":function(h){return g((h.Uf+1900)/100|0,2)},"%d":function(h){return g(h.lg,2)},"%e":function(h){return f(h.lg,2," ")},"%g":function(h){return q(h).toString().substring(2)},"%G":function(h){return q(h)},"%H":function(h){return g(h.bg,2)},"%I":function(h){h=h.bg;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){for(var w=0,x=0;x<=h.cg-1;w+=(Vb(h.Uf+1900)?Wb:Xb)[x++]);return g(h.lg+w,3)},"%m":function(h){return g(h.cg+1,2)},"%M":function(h){return g(h.Rg,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=
h.bg&&12>h.bg?"AM":"PM"},"%S":function(h){return g(h.Sg,2)},"%t":function(){return"\t"},"%u":function(h){return h.Pf||7},"%U":function(h){return g(Math.floor((h.Tf+7-h.Pf)/7),2)},"%V":function(h){var w=Math.floor((h.Tf+7-(h.Pf+6)%7)/7);2>=(h.Pf+371-h.Tf-2)%7&&w++;if(w)53==w&&(x=(h.Pf+371-h.Tf)%7,4==x||3==x&&Vb(h.Uf)||(w=1));else{w=52;var x=(h.Pf+7-h.Tf-1)%7;(4==x||5==x&&Vb(h.Uf%400-1))&&w++}return g(w,2)},"%w":function(h){return h.Pf},"%W":function(h){return g(Math.floor((h.Tf+7-(h.Pf+6)%7)/7),2)},
"%y":function(h){return(h.Uf+1900).toString().substring(2)},"%Y":function(h){return h.Uf+1900},"%z":function(h){h=h.Qg;var w=0<=h;h=Math.abs(h)/60;return(w?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.Tg},"%%":function(){return"%"}};d=d.replace(/%%/g,"\x00\x00");for(p in n)d.includes(p)&&(d=d.replace(new RegExp(p,"g"),n[p](e)));d=d.replace(/\0\0/g,"%");p=Za(d,!1);if(p.length>c)return 0;D.set(p,b);return p.length-1}
function rb(b,c,d,e){b||(b=this);this.parent=b;this.Qf=b.Qf;this.Zf=null;this.id=mb++;this.name=c;this.mode=d;this.If={};this.Jf={};this.rdev=e}Object.defineProperties(rb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(b){b?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(b){b?this.mode|=146:this.mode&=-147}},Lg:{get:function(){return 16384===(this.mode&61440)}},Kg:{get:function(){return 8192===(this.mode&61440)}}});Ib();
S=Array(4096);yb(Q,"/");V("/tmp",16895,0);V("/home",16895,0);V("/home/web_user",16895,0);(()=>{V("/dev",16895,0);bb(259,{read:()=>0,write:(c,d,e,f)=>f});zb("/dev/null",259);ab(1280,db);ab(1536,eb);zb("/dev/tty",1280);zb("/dev/tty1",1536);var b=Xa();W("/dev","random",b);W("/dev","urandom",b);V("/dev/shm",16895,0);V("/dev/shm/tmp",16895,0)})();
(()=>{V("/proc",16895,0);var b=V("/proc/self",16895,0);V("/proc/self/fd",16895,0);yb({Qf:()=>{var c=gb(b,"fd",16895,73);c.If={lookup:(d,e)=>{var f=lb[+e];if(!f)throw new P(8);d={parent:null,Qf:{vg:"fake"},If:{readlink:()=>f.path}};return d.parent=d}};return c}},"/proc/self/fd")})();var Qb;a.FS_createPath=Lb;a.FS_createDataFile=Nb;a.FS_createPreloadedFile=Rb;a.FS_unlink=Bb;a.FS_createLazyFile=Pb;a.FS_createDevice=W;
var Wc={p:function(b,c,d,e){z("Assertion failed: "+C(b)+", at: "+[c?C(c):"unknown filename",d,e?C(e):"unknown function"])},j:function(b){b=new La(b);b.Ag()||(b.jg(!0),Ja--);b.kg(!1);Ia.push(b);b.yg();return b.Bg()},m:function(){X(0);var b=Ia.pop();if(b.Ng()&&!b.sg()){var c=b.Jg();c&&N(c)(b.Yf);Zb(b.Yf)}M=0},ra:Na,a:Na,h:Na,z:Na,qa:Na,S:function(){var b=Ia.pop();b||z("no exception to throw");var c=b.Yf;b.sg()||(Ia.push(b),b.kg(!0),b.jg(!1),Ja++);M=c;throw c;},v:function(b,c,d){(new La(b)).Cg(c,d);
M=b;Ja++;throw b;},ia:function(){return Ja},d:function(b){M||(M=b);throw b;},ja:function(){return!0},J:function(){z("")},ka:function(){return Date.now()},ma:Qa,pa:function(b,c,d){pa.copyWithin(b,c,c+d)},la:function(){z("OOM")},na:function(b,c){var d=0;Sa().forEach(function(e,f){var g=c+d;f=G[b+4*f>>2]=g;for(g=0;g<e.length;++g)D[f++>>0]=e.charCodeAt(g);D[f>>0]=0;d+=e.length+1});return 0},oa:function(b,c){var d=Sa();G[b>>2]=d.length;var e=0;d.forEach(function(f){e+=f.length+1});G[c>>2]=e;return 0},
U:function(b){if(!noExitRuntime){if(a.onExit)a.onExit(b);ma=!0}ca(b,new ia(b))},R:function(b){try{var c=Tb(b);Fb(c);return 0}catch(d){if("undefined"==typeof Sb||"ErrnoError"!==d.name)throw d;return d.Xf}},Q:function(b,c,d,e){try{a:{var f=Tb(b);b=c;for(var g,k=c=0;k<d;k++){var l=G[b>>2],q=G[b+4>>2];b+=8;var n=f,p=l,r=q,A=g,h=D;if(0>r||0>A)throw new P(28);if(null===n.fd)throw new P(8);if(1===(n.flags&2097155))throw new P(8);if(16384===(n.node.mode&61440))throw new P(31);if(!n.Jf.read)throw new P(28);
var w="undefined"!=typeof A;if(!w)A=n.position;else if(!n.seekable)throw new P(70);var x=n.Jf.read(n,h,p,r,A);w||(n.position+=x);var B=x;if(0>B){var E=-1;break a}c+=B;if(B<q)break;"undefined"!==typeof g&&(g+=B)}E=c}G[e>>2]=E;return 0}catch(L){if("undefined"==typeof Sb||"ErrnoError"!==L.name)throw L;return L.Xf}},X:function(b,c,d,e,f){try{c=d+2097152>>>0<4194305-!!c?(c>>>0)+4294967296*d:NaN;if(isNaN(c))return 61;var g=Tb(b);Gb(g,c,e);Ga=[g.position>>>0,(K=g.position,1<=+Math.abs(K)?0<K?(Math.min(+Math.floor(K/
4294967296),4294967295)|0)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];F[f>>2]=Ga[0];F[f+4>>2]=Ga[1];g.eg&&0===c&&0===e&&(g.eg=null);return 0}catch(k){if("undefined"==typeof Sb||"ErrnoError"!==k.name)throw k;return k.Xf}},P:function(b,c,d,e){try{a:{var f=Tb(b);b=c;for(var g,k=c=0;k<d;k++){var l=G[b>>2],q=G[b+4>>2];b+=8;var n=Hb(f,D,l,q,g);if(0>n){var p=-1;break a}c+=n;"undefined"!==typeof g&&(g+=n)}p=c}G[e>>2]=p;return 0}catch(r){if("undefined"==typeof Sb||"ErrnoError"!==r.name)throw r;return r.Xf}},
fa:Ub,va:$b,A:ac,N:bc,M:cc,K:dc,E:ec,D:fc,O:gc,s:hc,b:ic,I:jc,ua:kc,i:mc,c:nc,t:oc,sa:pc,o:qc,ha:rc,q:sc,x:tc,H:uc,G:vc,ca:wc,_:xc,$:yc,aa:zc,W:Ac,ea:Bc,Z:Cc,V:Dc,k:Ec,l:Fc,C:Gc,f:Hc,L:Ic,ta:Jc,T:Kc,e:Lc,g:Mc,u:Nc,y:Oc,w:Pc,n:Qc,B:Rc,F:Sc,da:Tc,Y:Uc,ba:Vc,r:function(b){return b},ga:function(b,c,d,e){return Yb(b,c,d,e)}};
(function(){function b(d){d=d.exports;a.asm=d;la=a.asm.wa;var e=la.buffer;a.HEAP8=D=new Int8Array(e);a.HEAP16=new Int16Array(e);a.HEAP32=F=new Int32Array(e);a.HEAPU8=pa=new Uint8Array(e);a.HEAPU16=new Uint16Array(e);a.HEAPU32=G=new Uint32Array(e);a.HEAPF32=new Float32Array(e);a.HEAPF64=new Float64Array(e);ra=a.asm.ya;ta.unshift(a.asm.xa);za("wasm-instantiate");return d}var c={a:Wc};ya("wasm-instantiate");if(a.instantiateWasm)try{return a.instantiateWasm(c,b)}catch(d){return y("Module.instantiateWasm callback failed with error: "+
d),!1}Fa(c,function(d){b(d.instance)});return{}})();a._malloc=function(){return(a._malloc=a.asm.za).apply(null,arguments)};a._free=function(){return(a._free=a.asm.Aa).apply(null,arguments)};function Zb(){return(Zb=a.asm.Ba).apply(null,arguments)}a.__ZN7openmpt9exceptionC1ERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE=function(){return(a.__ZN7openmpt9exceptionC1ERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE=a.asm.Ca).apply(null,arguments)};
a.__ZN7openmpt9exceptionD1Ev=function(){return(a.__ZN7openmpt9exceptionD1Ev=a.asm.Da).apply(null,arguments)};a._openmpt_get_library_version=function(){return(a._openmpt_get_library_version=a.asm.Ea).apply(null,arguments)};a.__ZN7openmpt19get_library_versionEv=function(){return(a.__ZN7openmpt19get_library_versionEv=a.asm.Fa).apply(null,arguments)};a._openmpt_get_core_version=function(){return(a._openmpt_get_core_version=a.asm.Ga).apply(null,arguments)};
a.__ZN7openmpt16get_core_versionEv=function(){return(a.__ZN7openmpt16get_core_versionEv=a.asm.Ha).apply(null,arguments)};a._openmpt_free_string=function(){return(a._openmpt_free_string=a.asm.Ia).apply(null,arguments)};a._openmpt_get_string=function(){return(a._openmpt_get_string=a.asm.Ja).apply(null,arguments)};
a.__ZN7openmpt6string3getERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE=function(){return(a.__ZN7openmpt6string3getERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE=a.asm.Ka).apply(null,arguments)};a._openmpt_get_supported_extensions=function(){return(a._openmpt_get_supported_extensions=a.asm.La).apply(null,arguments)};a._openmpt_is_extension_supported=function(){return(a._openmpt_is_extension_supported=a.asm.Ma).apply(null,arguments)};
a._openmpt_log_func_default=function(){return(a._openmpt_log_func_default=a.asm.Na).apply(null,arguments)};a._openmpt_log_func_silent=function(){return(a._openmpt_log_func_silent=a.asm.Oa).apply(null,arguments)};a._openmpt_error_is_transient=function(){return(a._openmpt_error_is_transient=a.asm.Pa).apply(null,arguments)};a._openmpt_error_string=function(){return(a._openmpt_error_string=a.asm.Qa).apply(null,arguments)};
a._openmpt_error_func_default=function(){return(a._openmpt_error_func_default=a.asm.Ra).apply(null,arguments)};a._openmpt_error_func_log=function(){return(a._openmpt_error_func_log=a.asm.Sa).apply(null,arguments)};a._openmpt_error_func_store=function(){return(a._openmpt_error_func_store=a.asm.Ta).apply(null,arguments)};a._openmpt_error_func_ignore=function(){return(a._openmpt_error_func_ignore=a.asm.Ua).apply(null,arguments)};
a._openmpt_error_func_errno=function(){return(a._openmpt_error_func_errno=a.asm.Va).apply(null,arguments)};a._openmpt_error_func_errno_userdata=function(){return(a._openmpt_error_func_errno_userdata=a.asm.Wa).apply(null,arguments)};a._openmpt_could_open_probability=function(){return(a._openmpt_could_open_probability=a.asm.Xa).apply(null,arguments)};a._openmpt_could_open_probability2=function(){return(a._openmpt_could_open_probability2=a.asm.Ya).apply(null,arguments)};
a._openmpt_could_open_propability=function(){return(a._openmpt_could_open_propability=a.asm.Za).apply(null,arguments)};a._openmpt_probe_file_header_get_recommended_size=function(){return(a._openmpt_probe_file_header_get_recommended_size=a.asm._a).apply(null,arguments)};a._openmpt_probe_file_header=function(){return(a._openmpt_probe_file_header=a.asm.$a).apply(null,arguments)};
a._openmpt_probe_file_header_without_filesize=function(){return(a._openmpt_probe_file_header_without_filesize=a.asm.ab).apply(null,arguments)};a._openmpt_probe_file_header_from_stream=function(){return(a._openmpt_probe_file_header_from_stream=a.asm.bb).apply(null,arguments)};a._openmpt_module_create=function(){return(a._openmpt_module_create=a.asm.cb).apply(null,arguments)};a._openmpt_module_create2=function(){return(a._openmpt_module_create2=a.asm.db).apply(null,arguments)};
a._openmpt_module_create_from_memory=function(){return(a._openmpt_module_create_from_memory=a.asm.eb).apply(null,arguments)};a._openmpt_module_create_from_memory2=function(){return(a._openmpt_module_create_from_memory2=a.asm.fb).apply(null,arguments)};a._openmpt_module_destroy=function(){return(a._openmpt_module_destroy=a.asm.gb).apply(null,arguments)};a.__ZN7openmpt9exceptionD2Ev=function(){return(a.__ZN7openmpt9exceptionD2Ev=a.asm.hb).apply(null,arguments)};
a._openmpt_module_set_log_func=function(){return(a._openmpt_module_set_log_func=a.asm.ib).apply(null,arguments)};a.__ZN7openmpt9exceptionC2ERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE=function(){return(a.__ZN7openmpt9exceptionC2ERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE=a.asm.jb).apply(null,arguments)};a._openmpt_module_set_error_func=function(){return(a._openmpt_module_set_error_func=a.asm.kb).apply(null,arguments)};
a._openmpt_module_error_get_last=function(){return(a._openmpt_module_error_get_last=a.asm.lb).apply(null,arguments)};a._openmpt_module_error_get_last_message=function(){return(a._openmpt_module_error_get_last_message=a.asm.mb).apply(null,arguments)};a._openmpt_module_error_set_last=function(){return(a._openmpt_module_error_set_last=a.asm.nb).apply(null,arguments)};a._openmpt_module_error_clear=function(){return(a._openmpt_module_error_clear=a.asm.ob).apply(null,arguments)};
a._openmpt_module_select_subsong=function(){return(a._openmpt_module_select_subsong=a.asm.pb).apply(null,arguments)};a._openmpt_module_get_selected_subsong=function(){return(a._openmpt_module_get_selected_subsong=a.asm.qb).apply(null,arguments)};a._openmpt_module_set_repeat_count=function(){return(a._openmpt_module_set_repeat_count=a.asm.rb).apply(null,arguments)};a._openmpt_module_get_repeat_count=function(){return(a._openmpt_module_get_repeat_count=a.asm.sb).apply(null,arguments)};
a._openmpt_module_get_duration_seconds=function(){return(a._openmpt_module_get_duration_seconds=a.asm.tb).apply(null,arguments)};a._openmpt_module_set_position_seconds=function(){return(a._openmpt_module_set_position_seconds=a.asm.ub).apply(null,arguments)};a._openmpt_module_get_position_seconds=function(){return(a._openmpt_module_get_position_seconds=a.asm.vb).apply(null,arguments)};
a._openmpt_module_set_position_order_row=function(){return(a._openmpt_module_set_position_order_row=a.asm.wb).apply(null,arguments)};a._openmpt_module_get_render_param=function(){return(a._openmpt_module_get_render_param=a.asm.xb).apply(null,arguments)};a._openmpt_module_set_render_param=function(){return(a._openmpt_module_set_render_param=a.asm.yb).apply(null,arguments)};a._openmpt_module_read_mono=function(){return(a._openmpt_module_read_mono=a.asm.zb).apply(null,arguments)};
a._openmpt_module_read_stereo=function(){return(a._openmpt_module_read_stereo=a.asm.Ab).apply(null,arguments)};a._openmpt_module_read_quad=function(){return(a._openmpt_module_read_quad=a.asm.Bb).apply(null,arguments)};a._openmpt_module_read_float_mono=function(){return(a._openmpt_module_read_float_mono=a.asm.Cb).apply(null,arguments)};a._openmpt_module_read_float_stereo=function(){return(a._openmpt_module_read_float_stereo=a.asm.Db).apply(null,arguments)};
a._openmpt_module_read_float_quad=function(){return(a._openmpt_module_read_float_quad=a.asm.Eb).apply(null,arguments)};a._openmpt_module_read_interleaved_stereo=function(){return(a._openmpt_module_read_interleaved_stereo=a.asm.Fb).apply(null,arguments)};a._openmpt_module_read_interleaved_quad=function(){return(a._openmpt_module_read_interleaved_quad=a.asm.Gb).apply(null,arguments)};
a._openmpt_module_read_interleaved_float_stereo=function(){return(a._openmpt_module_read_interleaved_float_stereo=a.asm.Hb).apply(null,arguments)};a._openmpt_module_read_interleaved_float_quad=function(){return(a._openmpt_module_read_interleaved_float_quad=a.asm.Ib).apply(null,arguments)};a._openmpt_module_get_metadata_keys=function(){return(a._openmpt_module_get_metadata_keys=a.asm.Jb).apply(null,arguments)};
a._openmpt_module_get_metadata=function(){return(a._openmpt_module_get_metadata=a.asm.Kb).apply(null,arguments)};a._openmpt_module_get_current_estimated_bpm=function(){return(a._openmpt_module_get_current_estimated_bpm=a.asm.Lb).apply(null,arguments)};a._openmpt_module_get_current_speed=function(){return(a._openmpt_module_get_current_speed=a.asm.Mb).apply(null,arguments)};a._openmpt_module_get_current_tempo=function(){return(a._openmpt_module_get_current_tempo=a.asm.Nb).apply(null,arguments)};
a._openmpt_module_get_current_tempo2=function(){return(a._openmpt_module_get_current_tempo2=a.asm.Ob).apply(null,arguments)};a._openmpt_module_get_current_order=function(){return(a._openmpt_module_get_current_order=a.asm.Pb).apply(null,arguments)};a._openmpt_module_get_current_pattern=function(){return(a._openmpt_module_get_current_pattern=a.asm.Qb).apply(null,arguments)};a._openmpt_module_get_current_row=function(){return(a._openmpt_module_get_current_row=a.asm.Rb).apply(null,arguments)};
a._openmpt_module_get_current_playing_channels=function(){return(a._openmpt_module_get_current_playing_channels=a.asm.Sb).apply(null,arguments)};a._openmpt_module_get_current_channel_vu_mono=function(){return(a._openmpt_module_get_current_channel_vu_mono=a.asm.Tb).apply(null,arguments)};a._openmpt_module_get_current_channel_vu_left=function(){return(a._openmpt_module_get_current_channel_vu_left=a.asm.Ub).apply(null,arguments)};
a._openmpt_module_get_current_channel_vu_right=function(){return(a._openmpt_module_get_current_channel_vu_right=a.asm.Vb).apply(null,arguments)};a._openmpt_module_get_current_channel_vu_rear_left=function(){return(a._openmpt_module_get_current_channel_vu_rear_left=a.asm.Wb).apply(null,arguments)};a._openmpt_module_get_current_channel_vu_rear_right=function(){return(a._openmpt_module_get_current_channel_vu_rear_right=a.asm.Xb).apply(null,arguments)};
a._openmpt_module_get_num_subsongs=function(){return(a._openmpt_module_get_num_subsongs=a.asm.Yb).apply(null,arguments)};a._openmpt_module_get_num_channels=function(){return(a._openmpt_module_get_num_channels=a.asm.Zb).apply(null,arguments)};a._openmpt_module_get_num_orders=function(){return(a._openmpt_module_get_num_orders=a.asm._b).apply(null,arguments)};a._openmpt_module_get_num_patterns=function(){return(a._openmpt_module_get_num_patterns=a.asm.$b).apply(null,arguments)};
a._openmpt_module_get_num_instruments=function(){return(a._openmpt_module_get_num_instruments=a.asm.ac).apply(null,arguments)};a._openmpt_module_get_num_samples=function(){return(a._openmpt_module_get_num_samples=a.asm.bc).apply(null,arguments)};a._openmpt_module_get_subsong_name=function(){return(a._openmpt_module_get_subsong_name=a.asm.cc).apply(null,arguments)};a._openmpt_module_get_channel_name=function(){return(a._openmpt_module_get_channel_name=a.asm.dc).apply(null,arguments)};
a._openmpt_module_get_order_name=function(){return(a._openmpt_module_get_order_name=a.asm.ec).apply(null,arguments)};a._openmpt_module_get_pattern_name=function(){return(a._openmpt_module_get_pattern_name=a.asm.fc).apply(null,arguments)};a._openmpt_module_get_instrument_name=function(){return(a._openmpt_module_get_instrument_name=a.asm.gc).apply(null,arguments)};a._openmpt_module_get_sample_name=function(){return(a._openmpt_module_get_sample_name=a.asm.hc).apply(null,arguments)};
a._openmpt_module_get_order_pattern=function(){return(a._openmpt_module_get_order_pattern=a.asm.ic).apply(null,arguments)};a._openmpt_module_get_pattern_num_rows=function(){return(a._openmpt_module_get_pattern_num_rows=a.asm.jc).apply(null,arguments)};a._openmpt_module_get_pattern_row_channel_command=function(){return(a._openmpt_module_get_pattern_row_channel_command=a.asm.kc).apply(null,arguments)};
a._openmpt_module_format_pattern_row_channel_command=function(){return(a._openmpt_module_format_pattern_row_channel_command=a.asm.lc).apply(null,arguments)};a._openmpt_module_highlight_pattern_row_channel_command=function(){return(a._openmpt_module_highlight_pattern_row_channel_command=a.asm.mc).apply(null,arguments)};a._openmpt_module_format_pattern_row_channel=function(){return(a._openmpt_module_format_pattern_row_channel=a.asm.nc).apply(null,arguments)};
a._openmpt_module_highlight_pattern_row_channel=function(){return(a._openmpt_module_highlight_pattern_row_channel=a.asm.oc).apply(null,arguments)};a._openmpt_module_get_ctls=function(){return(a._openmpt_module_get_ctls=a.asm.pc).apply(null,arguments)};a._openmpt_module_ctl_get=function(){return(a._openmpt_module_ctl_get=a.asm.qc).apply(null,arguments)};a._openmpt_module_ctl_get_boolean=function(){return(a._openmpt_module_ctl_get_boolean=a.asm.rc).apply(null,arguments)};
a._openmpt_module_ctl_get_integer=function(){return(a._openmpt_module_ctl_get_integer=a.asm.sc).apply(null,arguments)};a._openmpt_module_ctl_get_floatingpoint=function(){return(a._openmpt_module_ctl_get_floatingpoint=a.asm.tc).apply(null,arguments)};a._openmpt_module_ctl_get_text=function(){return(a._openmpt_module_ctl_get_text=a.asm.uc).apply(null,arguments)};a._openmpt_module_ctl_set=function(){return(a._openmpt_module_ctl_set=a.asm.vc).apply(null,arguments)};
a._openmpt_module_ctl_set_boolean=function(){return(a._openmpt_module_ctl_set_boolean=a.asm.wc).apply(null,arguments)};a._openmpt_module_ctl_set_integer=function(){return(a._openmpt_module_ctl_set_integer=a.asm.xc).apply(null,arguments)};a._openmpt_module_ctl_set_floatingpoint=function(){return(a._openmpt_module_ctl_set_floatingpoint=a.asm.yc).apply(null,arguments)};a._openmpt_module_ctl_set_text=function(){return(a._openmpt_module_ctl_set_text=a.asm.zc).apply(null,arguments)};
a._openmpt_module_ext_create=function(){return(a._openmpt_module_ext_create=a.asm.Ac).apply(null,arguments)};a._openmpt_module_ext_create_from_memory=function(){return(a._openmpt_module_ext_create_from_memory=a.asm.Bc).apply(null,arguments)};a._openmpt_module_ext_destroy=function(){return(a._openmpt_module_ext_destroy=a.asm.Cc).apply(null,arguments)};a._openmpt_module_ext_get_module=function(){return(a._openmpt_module_ext_get_module=a.asm.Dc).apply(null,arguments)};
a._openmpt_module_ext_get_interface=function(){return(a._openmpt_module_ext_get_interface=a.asm.Ec).apply(null,arguments)};a.__ZNK7openmpt9exception4whatEv=function(){return(a.__ZNK7openmpt9exception4whatEv=a.asm.Fc).apply(null,arguments)};a.__ZN7openmpt9exceptionC2ERKS0_=function(){return(a.__ZN7openmpt9exceptionC2ERKS0_=a.asm.Gc).apply(null,arguments)};a.__ZN7openmpt9exceptionC2EOS0_=function(){return(a.__ZN7openmpt9exceptionC2EOS0_=a.asm.Hc).apply(null,arguments)};
a.__ZN7openmpt9exceptionaSERKS0_=function(){return(a.__ZN7openmpt9exceptionaSERKS0_=a.asm.Ic).apply(null,arguments)};a.__ZN7openmpt9exceptionaSEOS0_=function(){return(a.__ZN7openmpt9exceptionaSEOS0_=a.asm.Jc).apply(null,arguments)};a.__ZN7openmpt9exceptionD0Ev=function(){return(a.__ZN7openmpt9exceptionD0Ev=a.asm.Kc).apply(null,arguments)};a.__ZN7openmpt24get_supported_extensionsEv=function(){return(a.__ZN7openmpt24get_supported_extensionsEv=a.asm.Lc).apply(null,arguments)};
a.__ZN7openmpt22is_extension_supportedERKNSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE=function(){return(a.__ZN7openmpt22is_extension_supportedERKNSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE=a.asm.Mc).apply(null,arguments)};a.__ZN7openmpt23is_extension_supported2ENSt3__217basic_string_viewIcNS0_11char_traitsIcEEEE=function(){return(a.__ZN7openmpt23is_extension_supported2ENSt3__217basic_string_viewIcNS0_11char_traitsIcEEEE=a.asm.Nc).apply(null,arguments)};
a.__ZN7openmpt22could_open_probabilityERNSt3__213basic_istreamIcNS0_11char_traitsIcEEEEdRNS0_13basic_ostreamIcS3_EE=function(){return(a.__ZN7openmpt22could_open_probabilityERNSt3__213basic_istreamIcNS0_11char_traitsIcEEEEdRNS0_13basic_ostreamIcS3_EE=a.asm.Oc).apply(null,arguments)};
a.__ZN7openmpt22could_open_propabilityERNSt3__213basic_istreamIcNS0_11char_traitsIcEEEEdRNS0_13basic_ostreamIcS3_EE=function(){return(a.__ZN7openmpt22could_open_propabilityERNSt3__213basic_istreamIcNS0_11char_traitsIcEEEEdRNS0_13basic_ostreamIcS3_EE=a.asm.Pc).apply(null,arguments)};a.__ZN7openmpt38probe_file_header_get_recommended_sizeEv=function(){return(a.__ZN7openmpt38probe_file_header_get_recommended_sizeEv=a.asm.Qc).apply(null,arguments)};
a.__ZN7openmpt17probe_file_headerEyPKSt4bytemy=function(){return(a.__ZN7openmpt17probe_file_headerEyPKSt4bytemy=a.asm.Rc).apply(null,arguments)};a.__ZN7openmpt17probe_file_headerEyPKhmy=function(){return(a.__ZN7openmpt17probe_file_headerEyPKhmy=a.asm.Sc).apply(null,arguments)};a.__ZN7openmpt17probe_file_headerEyPKSt4bytem=function(){return(a.__ZN7openmpt17probe_file_headerEyPKSt4bytem=a.asm.Tc).apply(null,arguments)};
a.__ZN7openmpt17probe_file_headerEyPKhm=function(){return(a.__ZN7openmpt17probe_file_headerEyPKhm=a.asm.Uc).apply(null,arguments)};a.__ZN7openmpt17probe_file_headerEyRNSt3__213basic_istreamIcNS0_11char_traitsIcEEEE=function(){return(a.__ZN7openmpt17probe_file_headerEyRNSt3__213basic_istreamIcNS0_11char_traitsIcEEEE=a.asm.Vc).apply(null,arguments)};
a.__ZN7openmpt6moduleC2ERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEERNS1_13basic_ostreamIcS4_EERKNS1_3mapINS1_12basic_stringIcS4_NS1_9allocatorIcEEEESE_NS1_4lessISE_EENSC_INS1_4pairIKSE_SE_EEEEEE=function(){return(a.__ZN7openmpt6moduleC2ERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEERNS1_13basic_ostreamIcS4_EERKNS1_3mapINS1_12basic_stringIcS4_NS1_9allocatorIcEEEESE_NS1_4lessISE_EENSC_INS1_4pairIKSE_SE_EEEEEE=a.asm.Wc).apply(null,arguments)};
a.__ZN7openmpt6moduleC2ERKNSt3__26vectorISt4byteNS1_9allocatorIS3_EEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSB_NS4_IcEEEESH_NS1_4lessISH_EENS4_INS1_4pairIKSH_SH_EEEEEE=function(){return(a.__ZN7openmpt6moduleC2ERKNSt3__26vectorISt4byteNS1_9allocatorIS3_EEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSB_NS4_IcEEEESH_NS1_4lessISH_EENS4_INS1_4pairIKSH_SH_EEEEEE=a.asm.Xc).apply(null,arguments)};
a.__ZN7openmpt6moduleC2EPKSt4byteS3_RNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE=function(){return(a.__ZN7openmpt6moduleC2EPKSt4byteS3_RNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE=a.asm.Yc).apply(null,arguments)};
a.__ZN7openmpt6moduleC2EPKSt4bytemRNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE=function(){return(a.__ZN7openmpt6moduleC2EPKSt4bytemRNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE=a.asm.Zc).apply(null,arguments)};
a.__ZN7openmpt6moduleC2ERKNSt3__26vectorIhNS1_9allocatorIhEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_NS3_IcEEEESG_NS1_4lessISG_EENS3_INS1_4pairIKSG_SG_EEEEEE=function(){return(a.__ZN7openmpt6moduleC2ERKNSt3__26vectorIhNS1_9allocatorIhEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_NS3_IcEEEESG_NS1_4lessISG_EENS3_INS1_4pairIKSG_SG_EEEEEE=a.asm._c).apply(null,arguments)};
a.__ZN7openmpt6moduleC2EPKhS2_RNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=function(){return(a.__ZN7openmpt6moduleC2EPKhS2_RNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=a.asm.$c).apply(null,arguments)};
a.__ZN7openmpt6moduleC2EPKhmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=function(){return(a.__ZN7openmpt6moduleC2EPKhmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=a.asm.ad).apply(null,arguments)};
a.__ZN7openmpt6moduleC2ERKNSt3__26vectorIcNS1_9allocatorIcEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_S4_EESF_NS1_4lessISF_EENS3_INS1_4pairIKSF_SF_EEEEEE=function(){return(a.__ZN7openmpt6moduleC2ERKNSt3__26vectorIcNS1_9allocatorIcEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_S4_EESF_NS1_4lessISF_EENS3_INS1_4pairIKSF_SF_EEEEEE=a.asm.bd).apply(null,arguments)};
a.__ZN7openmpt6moduleC2EPKcS2_RNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=function(){return(a.__ZN7openmpt6moduleC2EPKcS2_RNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=a.asm.cd).apply(null,arguments)};
a.__ZN7openmpt6moduleC2EPKcmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=function(){return(a.__ZN7openmpt6moduleC2EPKcmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=a.asm.dd).apply(null,arguments)};
a.__ZN7openmpt6moduleC2EPKvmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=function(){return(a.__ZN7openmpt6moduleC2EPKvmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=a.asm.ed).apply(null,arguments)};a.__ZN7openmpt6moduleD2Ev=function(){return(a.__ZN7openmpt6moduleD2Ev=a.asm.fd).apply(null,arguments)};
a.__ZN7openmpt6moduleD0Ev=function(){return(a.__ZN7openmpt6moduleD0Ev=a.asm.gd).apply(null,arguments)};a.__ZN7openmpt6moduleD1Ev=function(){return(a.__ZN7openmpt6moduleD1Ev=a.asm.hd).apply(null,arguments)};a.__ZN7openmpt6module14select_subsongEi=function(){return(a.__ZN7openmpt6module14select_subsongEi=a.asm.id).apply(null,arguments)};a.__ZNK7openmpt6module20get_selected_subsongEv=function(){return(a.__ZNK7openmpt6module20get_selected_subsongEv=a.asm.jd).apply(null,arguments)};
a.__ZN7openmpt6module16set_repeat_countEi=function(){return(a.__ZN7openmpt6module16set_repeat_countEi=a.asm.kd).apply(null,arguments)};a.__ZNK7openmpt6module16get_repeat_countEv=function(){return(a.__ZNK7openmpt6module16get_repeat_countEv=a.asm.ld).apply(null,arguments)};a.__ZNK7openmpt6module20get_duration_secondsEv=function(){return(a.__ZNK7openmpt6module20get_duration_secondsEv=a.asm.md).apply(null,arguments)};
a.__ZN7openmpt6module20set_position_secondsEd=function(){return(a.__ZN7openmpt6module20set_position_secondsEd=a.asm.nd).apply(null,arguments)};a.__ZNK7openmpt6module20get_position_secondsEv=function(){return(a.__ZNK7openmpt6module20get_position_secondsEv=a.asm.od).apply(null,arguments)};a.__ZN7openmpt6module22set_position_order_rowEii=function(){return(a.__ZN7openmpt6module22set_position_order_rowEii=a.asm.pd).apply(null,arguments)};
a.__ZNK7openmpt6module16get_render_paramEi=function(){return(a.__ZNK7openmpt6module16get_render_paramEi=a.asm.qd).apply(null,arguments)};a.__ZN7openmpt6module16set_render_paramEii=function(){return(a.__ZN7openmpt6module16set_render_paramEii=a.asm.rd).apply(null,arguments)};a.__ZN7openmpt6module4readEimPs=function(){return(a.__ZN7openmpt6module4readEimPs=a.asm.sd).apply(null,arguments)};a.__ZN7openmpt6module4readEimPsS1_=function(){return(a.__ZN7openmpt6module4readEimPsS1_=a.asm.td).apply(null,arguments)};
a.__ZN7openmpt6module4readEimPsS1_S1_S1_=function(){return(a.__ZN7openmpt6module4readEimPsS1_S1_S1_=a.asm.ud).apply(null,arguments)};a.__ZN7openmpt6module4readEimPf=function(){return(a.__ZN7openmpt6module4readEimPf=a.asm.vd).apply(null,arguments)};a.__ZN7openmpt6module4readEimPfS1_=function(){return(a.__ZN7openmpt6module4readEimPfS1_=a.asm.wd).apply(null,arguments)};a.__ZN7openmpt6module4readEimPfS1_S1_S1_=function(){return(a.__ZN7openmpt6module4readEimPfS1_S1_S1_=a.asm.xd).apply(null,arguments)};
a.__ZN7openmpt6module23read_interleaved_stereoEimPs=function(){return(a.__ZN7openmpt6module23read_interleaved_stereoEimPs=a.asm.yd).apply(null,arguments)};a.__ZN7openmpt6module21read_interleaved_quadEimPs=function(){return(a.__ZN7openmpt6module21read_interleaved_quadEimPs=a.asm.zd).apply(null,arguments)};a.__ZN7openmpt6module23read_interleaved_stereoEimPf=function(){return(a.__ZN7openmpt6module23read_interleaved_stereoEimPf=a.asm.Ad).apply(null,arguments)};
a.__ZN7openmpt6module21read_interleaved_quadEimPf=function(){return(a.__ZN7openmpt6module21read_interleaved_quadEimPf=a.asm.Bd).apply(null,arguments)};a.__ZNK7openmpt6module17get_metadata_keysEv=function(){return(a.__ZNK7openmpt6module17get_metadata_keysEv=a.asm.Cd).apply(null,arguments)};
a.__ZNK7openmpt6module12get_metadataERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE=function(){return(a.__ZNK7openmpt6module12get_metadataERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE=a.asm.Dd).apply(null,arguments)};a.__ZNK7openmpt6module25get_current_estimated_bpmEv=function(){return(a.__ZNK7openmpt6module25get_current_estimated_bpmEv=a.asm.Ed).apply(null,arguments)};
a.__ZNK7openmpt6module17get_current_speedEv=function(){return(a.__ZNK7openmpt6module17get_current_speedEv=a.asm.Fd).apply(null,arguments)};a.__ZNK7openmpt6module17get_current_tempoEv=function(){return(a.__ZNK7openmpt6module17get_current_tempoEv=a.asm.Gd).apply(null,arguments)};a.__ZNK7openmpt6module18get_current_tempo2Ev=function(){return(a.__ZNK7openmpt6module18get_current_tempo2Ev=a.asm.Hd).apply(null,arguments)};
a.__ZNK7openmpt6module17get_current_orderEv=function(){return(a.__ZNK7openmpt6module17get_current_orderEv=a.asm.Id).apply(null,arguments)};a.__ZNK7openmpt6module19get_current_patternEv=function(){return(a.__ZNK7openmpt6module19get_current_patternEv=a.asm.Jd).apply(null,arguments)};a.__ZNK7openmpt6module15get_current_rowEv=function(){return(a.__ZNK7openmpt6module15get_current_rowEv=a.asm.Kd).apply(null,arguments)};
a.__ZNK7openmpt6module28get_current_playing_channelsEv=function(){return(a.__ZNK7openmpt6module28get_current_playing_channelsEv=a.asm.Ld).apply(null,arguments)};a.__ZNK7openmpt6module27get_current_channel_vu_monoEi=function(){return(a.__ZNK7openmpt6module27get_current_channel_vu_monoEi=a.asm.Md).apply(null,arguments)};a.__ZNK7openmpt6module27get_current_channel_vu_leftEi=function(){return(a.__ZNK7openmpt6module27get_current_channel_vu_leftEi=a.asm.Nd).apply(null,arguments)};
a.__ZNK7openmpt6module28get_current_channel_vu_rightEi=function(){return(a.__ZNK7openmpt6module28get_current_channel_vu_rightEi=a.asm.Od).apply(null,arguments)};a.__ZNK7openmpt6module32get_current_channel_vu_rear_leftEi=function(){return(a.__ZNK7openmpt6module32get_current_channel_vu_rear_leftEi=a.asm.Pd).apply(null,arguments)};a.__ZNK7openmpt6module33get_current_channel_vu_rear_rightEi=function(){return(a.__ZNK7openmpt6module33get_current_channel_vu_rear_rightEi=a.asm.Qd).apply(null,arguments)};
a.__ZNK7openmpt6module16get_num_subsongsEv=function(){return(a.__ZNK7openmpt6module16get_num_subsongsEv=a.asm.Rd).apply(null,arguments)};a.__ZNK7openmpt6module16get_num_channelsEv=function(){return(a.__ZNK7openmpt6module16get_num_channelsEv=a.asm.Sd).apply(null,arguments)};a.__ZNK7openmpt6module14get_num_ordersEv=function(){return(a.__ZNK7openmpt6module14get_num_ordersEv=a.asm.Td).apply(null,arguments)};
a.__ZNK7openmpt6module16get_num_patternsEv=function(){return(a.__ZNK7openmpt6module16get_num_patternsEv=a.asm.Ud).apply(null,arguments)};a.__ZNK7openmpt6module19get_num_instrumentsEv=function(){return(a.__ZNK7openmpt6module19get_num_instrumentsEv=a.asm.Vd).apply(null,arguments)};a.__ZNK7openmpt6module15get_num_samplesEv=function(){return(a.__ZNK7openmpt6module15get_num_samplesEv=a.asm.Wd).apply(null,arguments)};
a.__ZNK7openmpt6module17get_subsong_namesEv=function(){return(a.__ZNK7openmpt6module17get_subsong_namesEv=a.asm.Xd).apply(null,arguments)};a.__ZNK7openmpt6module17get_channel_namesEv=function(){return(a.__ZNK7openmpt6module17get_channel_namesEv=a.asm.Yd).apply(null,arguments)};a.__ZNK7openmpt6module15get_order_namesEv=function(){return(a.__ZNK7openmpt6module15get_order_namesEv=a.asm.Zd).apply(null,arguments)};
a.__ZNK7openmpt6module17get_pattern_namesEv=function(){return(a.__ZNK7openmpt6module17get_pattern_namesEv=a.asm._d).apply(null,arguments)};a.__ZNK7openmpt6module20get_instrument_namesEv=function(){return(a.__ZNK7openmpt6module20get_instrument_namesEv=a.asm.$d).apply(null,arguments)};a.__ZNK7openmpt6module16get_sample_namesEv=function(){return(a.__ZNK7openmpt6module16get_sample_namesEv=a.asm.ae).apply(null,arguments)};
a.__ZNK7openmpt6module17get_order_patternEi=function(){return(a.__ZNK7openmpt6module17get_order_patternEi=a.asm.be).apply(null,arguments)};a.__ZNK7openmpt6module20get_pattern_num_rowsEi=function(){return(a.__ZNK7openmpt6module20get_pattern_num_rowsEi=a.asm.ce).apply(null,arguments)};a.__ZNK7openmpt6module31get_pattern_row_channel_commandEiiii=function(){return(a.__ZNK7openmpt6module31get_pattern_row_channel_commandEiiii=a.asm.de).apply(null,arguments)};
a.__ZNK7openmpt6module34format_pattern_row_channel_commandEiiii=function(){return(a.__ZNK7openmpt6module34format_pattern_row_channel_commandEiiii=a.asm.ee).apply(null,arguments)};a.__ZNK7openmpt6module37highlight_pattern_row_channel_commandEiiii=function(){return(a.__ZNK7openmpt6module37highlight_pattern_row_channel_commandEiiii=a.asm.fe).apply(null,arguments)};
a.__ZNK7openmpt6module26format_pattern_row_channelEiiimb=function(){return(a.__ZNK7openmpt6module26format_pattern_row_channelEiiimb=a.asm.ge).apply(null,arguments)};a.__ZNK7openmpt6module29highlight_pattern_row_channelEiiimb=function(){return(a.__ZNK7openmpt6module29highlight_pattern_row_channelEiiimb=a.asm.he).apply(null,arguments)};a.__ZNK7openmpt6module8get_ctlsEv=function(){return(a.__ZNK7openmpt6module8get_ctlsEv=a.asm.ie).apply(null,arguments)};
a.__ZNK7openmpt6module7ctl_getERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE=function(){return(a.__ZNK7openmpt6module7ctl_getERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE=a.asm.je).apply(null,arguments)};a.__ZNK7openmpt6module15ctl_get_booleanENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE=function(){return(a.__ZNK7openmpt6module15ctl_get_booleanENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE=a.asm.ke).apply(null,arguments)};
a.__ZNK7openmpt6module15ctl_get_integerENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE=function(){return(a.__ZNK7openmpt6module15ctl_get_integerENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE=a.asm.le).apply(null,arguments)};a.__ZNK7openmpt6module21ctl_get_floatingpointENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE=function(){return(a.__ZNK7openmpt6module21ctl_get_floatingpointENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE=a.asm.me).apply(null,arguments)};
a.__ZNK7openmpt6module12ctl_get_textENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE=function(){return(a.__ZNK7openmpt6module12ctl_get_textENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE=a.asm.ne).apply(null,arguments)};a.__ZN7openmpt6module7ctl_setERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_=function(){return(a.__ZN7openmpt6module7ctl_setERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_=a.asm.oe).apply(null,arguments)};
a.__ZN7openmpt6module15ctl_set_booleanENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEEb=function(){return(a.__ZN7openmpt6module15ctl_set_booleanENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEEb=a.asm.pe).apply(null,arguments)};a.__ZN7openmpt6module15ctl_set_integerENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEEx=function(){return(a.__ZN7openmpt6module15ctl_set_integerENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEEx=a.asm.qe).apply(null,arguments)};
a.__ZN7openmpt6module21ctl_set_floatingpointENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEEd=function(){return(a.__ZN7openmpt6module21ctl_set_floatingpointENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEEd=a.asm.re).apply(null,arguments)};a.__ZN7openmpt6module12ctl_set_textENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEES5_=function(){return(a.__ZN7openmpt6module12ctl_set_textENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEES5_=a.asm.se).apply(null,arguments)};
a.__ZN7openmpt10module_extC2ERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEERNS1_13basic_ostreamIcS4_EERKNS1_3mapINS1_12basic_stringIcS4_NS1_9allocatorIcEEEESE_NS1_4lessISE_EENSC_INS1_4pairIKSE_SE_EEEEEE=function(){return(a.__ZN7openmpt10module_extC2ERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEERNS1_13basic_ostreamIcS4_EERKNS1_3mapINS1_12basic_stringIcS4_NS1_9allocatorIcEEEESE_NS1_4lessISE_EENSC_INS1_4pairIKSE_SE_EEEEEE=a.asm.te).apply(null,arguments)};
a.__ZN7openmpt10module_extC2ERKNSt3__26vectorIhNS1_9allocatorIhEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_NS3_IcEEEESG_NS1_4lessISG_EENS3_INS1_4pairIKSG_SG_EEEEEE=function(){return(a.__ZN7openmpt10module_extC2ERKNSt3__26vectorIhNS1_9allocatorIhEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_NS3_IcEEEESG_NS1_4lessISG_EENS3_INS1_4pairIKSG_SG_EEEEEE=a.asm.ue).apply(null,arguments)};
a.__ZN7openmpt10module_extC2ERKNSt3__26vectorIcNS1_9allocatorIcEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_S4_EESF_NS1_4lessISF_EENS3_INS1_4pairIKSF_SF_EEEEEE=function(){return(a.__ZN7openmpt10module_extC2ERKNSt3__26vectorIcNS1_9allocatorIcEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_S4_EESF_NS1_4lessISF_EENS3_INS1_4pairIKSF_SF_EEEEEE=a.asm.ve).apply(null,arguments)};
a.__ZN7openmpt10module_extC2ERKNSt3__26vectorISt4byteNS1_9allocatorIS3_EEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSB_NS4_IcEEEESH_NS1_4lessISH_EENS4_INS1_4pairIKSH_SH_EEEEEE=function(){return(a.__ZN7openmpt10module_extC2ERKNSt3__26vectorISt4byteNS1_9allocatorIS3_EEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSB_NS4_IcEEEESH_NS1_4lessISH_EENS4_INS1_4pairIKSH_SH_EEEEEE=a.asm.we).apply(null,arguments)};
a.__ZN7openmpt10module_extC2EPKhmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=function(){return(a.__ZN7openmpt10module_extC2EPKhmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=a.asm.xe).apply(null,arguments)};
a.__ZN7openmpt10module_extC2EPKcmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=function(){return(a.__ZN7openmpt10module_extC2EPKcmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=a.asm.ye).apply(null,arguments)};
a.__ZN7openmpt10module_extC2EPKSt4bytemRNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE=function(){return(a.__ZN7openmpt10module_extC2EPKSt4bytemRNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE=a.asm.ze).apply(null,arguments)};
a.__ZN7openmpt10module_extC2EPKvmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=function(){return(a.__ZN7openmpt10module_extC2EPKvmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=a.asm.Ae).apply(null,arguments)};
a.__ZN7openmpt10module_extD2Ev=function(){return(a.__ZN7openmpt10module_extD2Ev=a.asm.Be).apply(null,arguments)};a.__ZN7openmpt10module_extD0Ev=function(){return(a.__ZN7openmpt10module_extD0Ev=a.asm.Ce).apply(null,arguments)};a.__ZN7openmpt10module_extD1Ev=function(){return(a.__ZN7openmpt10module_extD1Ev=a.asm.De).apply(null,arguments)};a.__ZN7openmpt10module_extC2ERKS0_=function(){return(a.__ZN7openmpt10module_extC2ERKS0_=a.asm.Ee).apply(null,arguments)};
a.__ZN7openmpt10module_extaSERKS0_=function(){return(a.__ZN7openmpt10module_extaSERKS0_=a.asm.Fe).apply(null,arguments)};a.__ZN7openmpt10module_ext13get_interfaceERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE=function(){return(a.__ZN7openmpt10module_ext13get_interfaceERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE=a.asm.Ge).apply(null,arguments)};
a.__ZN7openmpt10module_extC1EPKSt4bytemRNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE=function(){return(a.__ZN7openmpt10module_extC1EPKSt4bytemRNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE=a.asm.He).apply(null,arguments)};
a.__ZN7openmpt10module_extC1EPKcmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=function(){return(a.__ZN7openmpt10module_extC1EPKcmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=a.asm.Ie).apply(null,arguments)};
a.__ZN7openmpt10module_extC1EPKhmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=function(){return(a.__ZN7openmpt10module_extC1EPKhmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=a.asm.Je).apply(null,arguments)};
a.__ZN7openmpt10module_extC1EPKvmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=function(){return(a.__ZN7openmpt10module_extC1EPKvmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=a.asm.Ke).apply(null,arguments)};
a.__ZN7openmpt10module_extC1ERKNSt3__26vectorISt4byteNS1_9allocatorIS3_EEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSB_NS4_IcEEEESH_NS1_4lessISH_EENS4_INS1_4pairIKSH_SH_EEEEEE=function(){return(a.__ZN7openmpt10module_extC1ERKNSt3__26vectorISt4byteNS1_9allocatorIS3_EEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSB_NS4_IcEEEESH_NS1_4lessISH_EENS4_INS1_4pairIKSH_SH_EEEEEE=a.asm.Le).apply(null,arguments)};
a.__ZN7openmpt10module_extC1ERKNSt3__26vectorIcNS1_9allocatorIcEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_S4_EESF_NS1_4lessISF_EENS3_INS1_4pairIKSF_SF_EEEEEE=function(){return(a.__ZN7openmpt10module_extC1ERKNSt3__26vectorIcNS1_9allocatorIcEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_S4_EESF_NS1_4lessISF_EENS3_INS1_4pairIKSF_SF_EEEEEE=a.asm.Me).apply(null,arguments)};
a.__ZN7openmpt10module_extC1ERKNSt3__26vectorIhNS1_9allocatorIhEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_NS3_IcEEEESG_NS1_4lessISG_EENS3_INS1_4pairIKSG_SG_EEEEEE=function(){return(a.__ZN7openmpt10module_extC1ERKNSt3__26vectorIhNS1_9allocatorIhEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_NS3_IcEEEESG_NS1_4lessISG_EENS3_INS1_4pairIKSG_SG_EEEEEE=a.asm.Ne).apply(null,arguments)};
a.__ZN7openmpt10module_extC1ERKS0_=function(){return(a.__ZN7openmpt10module_extC1ERKS0_=a.asm.Oe).apply(null,arguments)};
a.__ZN7openmpt10module_extC1ERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEERNS1_13basic_ostreamIcS4_EERKNS1_3mapINS1_12basic_stringIcS4_NS1_9allocatorIcEEEESE_NS1_4lessISE_EENSC_INS1_4pairIKSE_SE_EEEEEE=function(){return(a.__ZN7openmpt10module_extC1ERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEERNS1_13basic_ostreamIcS4_EERKNS1_3mapINS1_12basic_stringIcS4_NS1_9allocatorIcEEEESE_NS1_4lessISE_EENSC_INS1_4pairIKSE_SE_EEEEEE=a.asm.Pe).apply(null,arguments)};
a.__ZN7openmpt6moduleC1EPKSt4byteS3_RNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE=function(){return(a.__ZN7openmpt6moduleC1EPKSt4byteS3_RNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE=a.asm.Qe).apply(null,arguments)};
a.__ZN7openmpt6moduleC1EPKSt4bytemRNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE=function(){return(a.__ZN7openmpt6moduleC1EPKSt4bytemRNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE=a.asm.Re).apply(null,arguments)};
a.__ZN7openmpt6moduleC1EPKcS2_RNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=function(){return(a.__ZN7openmpt6moduleC1EPKcS2_RNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=a.asm.Se).apply(null,arguments)};
a.__ZN7openmpt6moduleC1EPKcmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=function(){return(a.__ZN7openmpt6moduleC1EPKcmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=a.asm.Te).apply(null,arguments)};
a.__ZN7openmpt6moduleC1EPKhS2_RNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=function(){return(a.__ZN7openmpt6moduleC1EPKhS2_RNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=a.asm.Ue).apply(null,arguments)};
a.__ZN7openmpt6moduleC1EPKhmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=function(){return(a.__ZN7openmpt6moduleC1EPKhmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=a.asm.Ve).apply(null,arguments)};
a.__ZN7openmpt6moduleC1EPKvmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=function(){return(a.__ZN7openmpt6moduleC1EPKvmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE=a.asm.We).apply(null,arguments)};
a.__ZN7openmpt6moduleC1ERKNSt3__26vectorISt4byteNS1_9allocatorIS3_EEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSB_NS4_IcEEEESH_NS1_4lessISH_EENS4_INS1_4pairIKSH_SH_EEEEEE=function(){return(a.__ZN7openmpt6moduleC1ERKNSt3__26vectorISt4byteNS1_9allocatorIS3_EEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSB_NS4_IcEEEESH_NS1_4lessISH_EENS4_INS1_4pairIKSH_SH_EEEEEE=a.asm.Xe).apply(null,arguments)};
a.__ZN7openmpt6moduleC1ERKNSt3__26vectorIcNS1_9allocatorIcEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_S4_EESF_NS1_4lessISF_EENS3_INS1_4pairIKSF_SF_EEEEEE=function(){return(a.__ZN7openmpt6moduleC1ERKNSt3__26vectorIcNS1_9allocatorIcEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_S4_EESF_NS1_4lessISF_EENS3_INS1_4pairIKSF_SF_EEEEEE=a.asm.Ye).apply(null,arguments)};
a.__ZN7openmpt6moduleC1ERKNSt3__26vectorIhNS1_9allocatorIhEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_NS3_IcEEEESG_NS1_4lessISG_EENS3_INS1_4pairIKSG_SG_EEEEEE=function(){return(a.__ZN7openmpt6moduleC1ERKNSt3__26vectorIhNS1_9allocatorIhEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_NS3_IcEEEESG_NS1_4lessISG_EENS3_INS1_4pairIKSG_SG_EEEEEE=a.asm.Ze).apply(null,arguments)};
a.__ZN7openmpt6moduleC1ERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEERNS1_13basic_ostreamIcS4_EERKNS1_3mapINS1_12basic_stringIcS4_NS1_9allocatorIcEEEESE_NS1_4lessISE_EENSC_INS1_4pairIKSE_SE_EEEEEE=function(){return(a.__ZN7openmpt6moduleC1ERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEERNS1_13basic_ostreamIcS4_EERKNS1_3mapINS1_12basic_stringIcS4_NS1_9allocatorIcEEEESE_NS1_4lessISE_EENSC_INS1_4pairIKSE_SE_EEEEEE=a.asm._e).apply(null,arguments)};
a.__ZN7openmpt9exceptionC1EOS0_=function(){return(a.__ZN7openmpt9exceptionC1EOS0_=a.asm.$e).apply(null,arguments)};a.__ZN7openmpt9exceptionC1ERKS0_=function(){return(a.__ZN7openmpt9exceptionC1ERKS0_=a.asm.af).apply(null,arguments)};a._emu_load_file=function(){return(a._emu_load_file=a.asm.bf).apply(null,arguments)};a._emu_teardown=function(){return(a._emu_teardown=a.asm.cf).apply(null,arguments)};a._emu_get_sample_rate=function(){return(a._emu_get_sample_rate=a.asm.df).apply(null,arguments)};
a._emu_set_subsong=function(){return(a._emu_set_subsong=a.asm.ef).apply(null,arguments)};a._emu_get_track_info=function(){return(a._emu_get_track_info=a.asm.ff).apply(null,arguments)};a._emu_compute_audio_samples=function(){return(a._emu_compute_audio_samples=a.asm.gf).apply(null,arguments)};a._emu_get_audio_buffer=function(){return(a._emu_get_audio_buffer=a.asm.hf).apply(null,arguments)};a._emu_get_audio_buffer_length=function(){return(a._emu_get_audio_buffer_length=a.asm.jf).apply(null,arguments)};
a._emu_get_current_position=function(){return(a._emu_get_current_position=a.asm.kf).apply(null,arguments)};a._emu_seek_position=function(){return(a._emu_seek_position=a.asm.lf).apply(null,arguments)};a._emu_get_max_position=function(){return(a._emu_get_max_position=a.asm.mf).apply(null,arguments)};a._emu_number_trace_streams=function(){return(a._emu_number_trace_streams=a.asm.nf).apply(null,arguments)};a._emu_get_trace_streams=function(){return(a._emu_get_trace_streams=a.asm.of).apply(null,arguments)};
function X(){return(X=a.asm.pf).apply(null,arguments)}function Oa(){return(Oa=a.asm.qf).apply(null,arguments)}function Y(){return(Y=a.asm.rf).apply(null,arguments)}function Z(){return(Z=a.asm.sf).apply(null,arguments)}function Xc(){return(Xc=a.asm.tf).apply(null,arguments)}function Pa(){return(Pa=a.asm.uf).apply(null,arguments)}function Ma(){return(Ma=a.asm.vf).apply(null,arguments)}
var Yc=a.dynCall_ji=function(){return(Yc=a.dynCall_ji=a.asm.wf).apply(null,arguments)},Zc=a.dynCall_viiiji=function(){return(Zc=a.dynCall_viiiji=a.asm.xf).apply(null,arguments)},$c=a.dynCall_iiji=function(){return($c=a.dynCall_iiji=a.asm.yf).apply(null,arguments)},ad=a.dynCall_ijiij=function(){return(ad=a.dynCall_ijiij=a.asm.zf).apply(null,arguments)},bd=a.dynCall_ijii=function(){return(bd=a.dynCall_ijii=a.asm.Af).apply(null,arguments)},cd=a.dynCall_iji=function(){return(cd=a.dynCall_iji=a.asm.Bf).apply(null,
arguments)},dd=a.dynCall_jiii=function(){return(dd=a.dynCall_jiii=a.asm.Cf).apply(null,arguments)},ed=a.dynCall_viiji=function(){return(ed=a.dynCall_viiji=a.asm.Df).apply(null,arguments)},fd=a.dynCall_j=function(){return(fd=a.dynCall_j=a.asm.Ef).apply(null,arguments)},gd=a.dynCall_viijii=function(){return(gd=a.dynCall_viijii=a.asm.Ff).apply(null,arguments)},hd=a.dynCall_jiiii=function(){return(hd=a.dynCall_jiiii=a.asm.Gf).apply(null,arguments)};
function qc(b,c,d,e,f){var g=Y();try{return N(b)(c,d,e,f)}catch(k){Z(g);if(k!==k+0)throw k;X(1,0)}}function nc(b,c,d,e){var f=Y();try{return N(b)(c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;X(1,0)}}function Hc(b,c,d){var e=Y();try{N(b)(c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function ic(b,c){var d=Y();try{return N(b)(c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function Lc(b,c,d,e){var f=Y();try{N(b)(c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;X(1,0)}}
function Ec(b){var c=Y();try{N(b)()}catch(d){Z(c);if(d!==d+0)throw d;X(1,0)}}function mc(b,c,d){var e=Y();try{return N(b)(c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function hc(b){var c=Y();try{return N(b)()}catch(d){Z(c);if(d!==d+0)throw d;X(1,0)}}function Fc(b,c){var d=Y();try{N(b)(c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function sc(b,c,d,e,f,g){var k=Y();try{return N(b)(c,d,e,f,g)}catch(l){Z(k);if(l!==l+0)throw l;X(1,0)}}
function Mc(b,c,d,e,f){var g=Y();try{N(b)(c,d,e,f)}catch(k){Z(g);if(k!==k+0)throw k;X(1,0)}}function fc(b,c,d){var e=Y();try{return N(b)(c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function Kc(b,c,d,e){var f=Y();try{N(b)(c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;X(1,0)}}function Nc(b,c,d,e,f,g){var k=Y();try{N(b)(c,d,e,f,g)}catch(l){Z(k);if(l!==l+0)throw l;X(1,0)}}function tc(b,c,d,e,f,g,k){var l=Y();try{return N(b)(c,d,e,f,g,k)}catch(q){Z(l);if(q!==q+0)throw q;X(1,0)}}
function Oc(b,c,d,e,f,g,k){var l=Y();try{N(b)(c,d,e,f,g,k)}catch(q){Z(l);if(q!==q+0)throw q;X(1,0)}}function Gc(b,c,d){var e=Y();try{N(b)(c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function $b(b,c){var d=Y();try{return N(b)(c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function oc(b,c,d,e,f){var g=Y();try{return N(b)(c,d,e,f)}catch(k){Z(g);if(k!==k+0)throw k;X(1,0)}}function Pc(b,c,d,e,f,g,k,l){var q=Y();try{N(b)(c,d,e,f,g,k,l)}catch(n){Z(q);if(n!==n+0)throw n;X(1,0)}}
function Qc(b,c,d,e,f,g,k,l,q,n){var p=Y();try{N(b)(c,d,e,f,g,k,l,q,n)}catch(r){Z(p);if(r!==r+0)throw r;X(1,0)}}function bc(b,c,d){var e=Y();try{return N(b)(c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function jc(b,c,d){var e=Y();try{return N(b)(c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function kc(b,c,d,e,f,g){var k=Y();try{return N(b)(c,d,e,f,g)}catch(l){Z(k);if(l!==l+0)throw l;X(1,0)}}function cc(b,c,d,e){var f=Y();try{return N(b)(c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;X(1,0)}}
function ec(b,c,d,e){var f=Y();try{return N(b)(c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;X(1,0)}}function ac(b,c){var d=Y();try{return N(b)(c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function uc(b,c,d,e,f,g,k,l){var q=Y();try{return N(b)(c,d,e,f,g,k,l)}catch(n){Z(q);if(n!==n+0)throw n;X(1,0)}}function Jc(b,c,d,e,f){var g=Y();try{N(b)(c,d,e,f)}catch(k){Z(g);if(k!==k+0)throw k;X(1,0)}}function Ic(b,c,d,e){var f=Y();try{N(b)(c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;X(1,0)}}
function dc(b,c,d){var e=Y();try{return N(b)(c,d)}catch(f){Z(e);if(f!==f+0)throw f;X(1,0)}}function pc(b,c,d,e,f,g){var k=Y();try{return N(b)(c,d,e,f,g)}catch(l){Z(k);if(l!==l+0)throw l;X(1,0)}}function rc(b,c,d,e,f,g){var k=Y();try{return N(b)(c,d,e,f,g)}catch(l){Z(k);if(l!==l+0)throw l;X(1,0)}}function gc(b,c,d,e){var f=Y();try{return N(b)(c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;X(1,0)}}
function vc(b,c,d,e,f,g,k,l,q,n,p,r){var A=Y();try{return N(b)(c,d,e,f,g,k,l,q,n,p,r)}catch(h){Z(A);if(h!==h+0)throw h;X(1,0)}}function Rc(b,c,d,e,f,g,k,l,q,n,p){var r=Y();try{N(b)(c,d,e,f,g,k,l,q,n,p)}catch(A){Z(r);if(A!==A+0)throw A;X(1,0)}}function Sc(b,c,d,e,f,g,k,l,q,n,p,r,A,h,w,x){var B=Y();try{N(b)(c,d,e,f,g,k,l,q,n,p,r,A,h,w,x)}catch(E){Z(B);if(E!==E+0)throw E;X(1,0)}}function Bc(b,c){var d=Y();try{return Yc(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}
function Tc(b,c,d,e,f,g,k){var l=Y();try{Zc(b,c,d,e,f,g,k)}catch(q){Z(l);if(q!==q+0)throw q;X(1,0)}}function wc(b,c,d,e,f){var g=Y();try{return $c(b,c,d,e,f)}catch(k){Z(g);if(k!==k+0)throw k;X(1,0)}}function Vc(b,c,d,e,f,g,k){var l=Y();try{gd(b,c,d,e,f,g,k)}catch(q){Z(l);if(q!==q+0)throw q;X(1,0)}}function zc(b,c,d,e,f,g,k){var l=Y();try{return ad(b,c,d,e,f,g,k)}catch(q){Z(l);if(q!==q+0)throw q;X(1,0)}}
function yc(b,c,d,e,f){var g=Y();try{return bd(b,c,d,e,f)}catch(k){Z(g);if(k!==k+0)throw k;X(1,0)}}function xc(b,c,d,e){var f=Y();try{return cd(b,c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;X(1,0)}}function Cc(b,c,d,e){var f=Y();try{return dd(b,c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;X(1,0)}}function Uc(b,c,d,e,f,g){var k=Y();try{ed(b,c,d,e,f,g)}catch(l){Z(k);if(l!==l+0)throw l;X(1,0)}}function Ac(b){var c=Y();try{return fd(b)}catch(d){Z(c);if(d!==d+0)throw d;X(1,0)}}
function Dc(b,c,d,e,f){var g=Y();try{return hd(b,c,d,e,f)}catch(k){Z(g);if(k!==k+0)throw k;X(1,0)}}a.UTF8ToString=C;a.addRunDependency=ya;a.removeRunDependency=za;a.FS_createPath=Lb;a.FS_createDataFile=Nb;a.FS_createPreloadedFile=Rb;a.FS_createLazyFile=Pb;a.FS_createDevice=W;a.FS_unlink=Bb;
a.ccall=function(b,c,d,e){var f={string:n=>{var p=0;if(null!==n&&void 0!==n&&0!==n){var r=(n.length<<2)+1;p=Xc(r);qa(n,pa,p,r)}return p},array:n=>{var p=Xc(n.length);D.set(n,p);return p}};b=a["_"+b];var g=[],k=0;if(e)for(var l=0;l<e.length;l++){var q=f[d[l]];q?(0===k&&(k=Y()),g[l]=q(e[l])):g[l]=e[l]}d=b.apply(null,g);return d=function(n){0!==k&&Z(k);return"string"===c?C(n):"boolean"===c?!!n:n}(d)};var jd;xa=function kd(){jd||ld();jd||(xa=kd)};
function ld(){function b(){if(!jd&&(jd=!0,a.calledRun=!0,!ma)){a.noFSInit||Jb||(Jb=!0,Ib(),a.stdin=a.stdin,a.stdout=a.stdout,a.stderr=a.stderr,a.stdin?W("/dev","stdin",a.stdin):Ab("/dev/tty","/dev/stdin"),a.stdout?W("/dev","stdout",null,a.stdout):Ab("/dev/tty","/dev/stdout"),a.stderr?W("/dev","stderr",null,a.stderr):Ab("/dev/tty1","/dev/stderr"),Eb("/dev/stdin",0),Eb("/dev/stdout",1),Eb("/dev/stderr",1));nb=!1;Ha(ta);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==
typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();ua.unshift(c)}Ha(ua)}}if(!(0<I)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)va();Ha(sa);0<I||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();ld();
  return {
	Module: Module,  // expose original Module
  };
})(window.spp_backend_state_mpt);
/*
 mpt_adapter.js: Adapts "libopenmpt" backend to generic WebAudio/ScriptProcessor player.

 version 1.1

 	Copyright (C) 2018-2023 Juergen Wothke

 LICENSE
    The code is licensed under the BSD license.
*/
class MPTBackendAdapter extends EmsHEAP16BackendAdapter {
	constructor()
	{
		super(backend_mpt.Module, 2,
				new SimpleFileMapper(backend_mpt.Module),
				new HEAP32ScopeProvider(backend_mpt.Module, 0x8000));

		this._scopeEnabled = false;

		this.ensureReadyNotification();
	}

	enableScope(enable)
	{
		this._scopeEnabled= enable;
	}

	loadMusicData(sampleRate, path, filename, data, options)
	{
		filename = this._getFilename(path, filename);

		let ret = this._loadMusicDataBuffer(filename, data, ScriptNodePlayer.getWebAudioSampleRate(), -999, this._scopeEnabled);

		if (ret == 0)
		{
			this._setupOutputResampling(sampleRate);
		}
		return ret;
	}

	evalTrackOptions(options)
	{
		super.evalTrackOptions(options);

		let id = (options && options.track) ? options.track : 0;
		return this.Module.ccall('emu_set_subsong', 'number', ['number'], [id]);
	}

	getSongInfoMeta()
	{
		return {
			title: String,
			artist: String,
			type: String,
			msg: String,
			tracker: String,
			tracks: String,
		};
	}

	updateSongInfo(filename)
	{
		let result = this._songInfo;

		let numAttr = 6;
		let ret = this.Module.ccall('emu_get_track_info', 'number');

		let array = this.Module.HEAP32.subarray(ret>>2, (ret>>2)+numAttr);

		result.title = this.Module.UTF8ToString(array[0]);
		if (!result.title.length) result.title = filename.replace(/^.*[\\\/]/, '');

		result.artist = this.Module.UTF8ToString(array[1]);
		result.type = this.Module.UTF8ToString(array[2]);
		result.msg = this.Module.UTF8ToString(array[3]);
		result.tracker = this.Module.UTF8ToString(array[4]);
		result.tracks = this.Module.UTF8ToString(array[5]);
	}

};
