import { readdirSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const BANNER_DIR = resolve(__dirname, '../public/img/banner');

/**
 * Discovers the hero banners generated by cms/scripts/processBanners.js and
 * returns them in a random order.
 *
 * The directory read happens inside the export rather than at module scope, so
 * a running dev server picks up newly added banners without a restart.
 */
export default function () {
  if (!existsSync(BANNER_DIR)) return [];

  const byName = new Map();
  for (const file of readdirSync(BANNER_DIR)) {
    const match = file.match(/^(.+)-(\d+)\.webp$/);
    if (!match) continue;
    const [, name, width] = match;
    if (!byName.has(name)) byName.set(name, []);
    byName.get(name).push(Number(width));
  }

  const banners = [...byName.entries()].map(([name, widths]) => {
    const sorted = widths.sort((a, b) => a - b);
    return {
      name,
      widths: sorted,
      srcset: sorted.map((w) => `/img/banner/${name}-${w}.webp ${w}w`).join(', '),
      src: `/img/banner/${name}-${sorted[sorted.length - 1]}.webp`,
    };
  });

  for (let i = banners.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [banners[i], banners[j]] = [banners[j], banners[i]];
  }

  return banners;
}
