name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Fetch content from Contentful
      env:
        DELIVERY_TOKEN: ${{ secrets.DELIVERY_TOKEN }}
        MANAGEMENT_TOKEN: ${{ secrets.MANAGEMENT_TOKEN }}
        NODE_ENV: production
      run: npm run build:content
    
    - name: Build production site
      env:
        NODE_ENV: production
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: site-build
        path: dist/
        retention-days: 30
